### ISSUE TITLE
Trying to use mongoose with node-webkit target on Webpack

### ISSUE THREAD

**Issue by cloppy** [webpack/webpack#1040]
I tried to get an answer on StackOverflow, but nobody seemed to have an idea. So I post this as a bug, since I can't get it to work:

I use webpack and target it's build output for `node-webkit`. I want to require the `mongoose` module inside my project to connect to mongodb, but it always states some errors when I try to pack the project:

    WARNING in ./~/mongoose/~/mongodb/~/mongodb-core/~/bson/~/bson-ext/ext/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./win32/x64/bson in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/ext
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/bson/~/bson-ext/ext/index.js 6:10-37
    
    WARNING in ./~/mongoose/~/mongodb/~/mongodb-core/~/bson/~/bson-ext/ext/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./win32/ia32/bson in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/ext
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/bson/~/bson-ext/ext/index.js 8:10-38
    
    WARNING in ./~/mongoose/~/mongodb/~/mongodb-core/~/bson/~/bson-ext/ext/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/bson in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/ext
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/bson/~/bson-ext/ext/index.js 10:10-42 15:9-41
    
    ERROR in ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/kerberos.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/kerberos in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/lib
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/kerberos.js 1:15-51
    
    ERROR in ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_credentials.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/lib/win32/wrappers
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_credentials.js 1:32-74
    
    ERROR in ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_context.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/lib/win32/wrappers
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_context.js 1:28-70
    
    ERROR in ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_buffer.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/lib/win32/wrappers
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_buffer.js 1:27-69
    
    ERROR in ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/lib/win32/wrappers
     @ ./~/mongoose/~/mongodb/~/mongodb-core/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js 1:37-79

It seems like webpack is unable to load `.node` files, so I installed the `node-loader` and added to my webpack.config.js:

    module.exports = {
        entry: './ui/index.jsx',
        target: 'node-webkit',
        output: {
            path: __dirname + '/build-ui',
            filename: 'app.js',
            publicPath: '/assets/'
        },
        module: {
            loaders: [
                {
                    test: /\.jsx$/,
                    loader: 'jsx-loader?insertPragma=React.DOM&harmony'
                },
                {
                    test: /\.css$/,
                    loader: "style-loader!css-loader"
                },
                {
                    test: /\.scss$/,
                    loader: "style-loader!css-loader!sass-loader"
                },
                {
                    test: /\.(png|jpg)$/,
                    loader: 'url-loader?limit=8192'
                },
                {
                    test: /\.json$/,
                    loader: "json-loader"
                },
                {
                    test: /\.target.mk$/,
                    loader: "raw-loader"
                },
                {
                    test: /\.node$/,
                    loader: "node-loader"
                }
            ]
        },
        resolve: {
            extensions: ['', '.js', '.jsx']
        }
    };

But it still throws that errors and warnings. Am I missing something? Or is this a bug?

**Comment by cloppy** [comment]
Ah never mind, I fixed the issue. Just forogt to add `.node` to the `resolve.extensions` array.

**Comment by 0x80** [comment]
I'm trying to do the same but I'm getting this:

```
WARNING in ./~/mongoose/~/bson/~/bson-ext/ext/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./win32/x64/bson in /Users/thijskoerselman/Development/Nupky/webpack/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/ext
 @ ./~/mongoose/~/bson/~/bson-ext/ext/index.js 6:10-37

WARNING in ./~/mongoose/~/bson/~/bson-ext/ext/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./win32/ia32/bson in /Users/thijskoerselman/Development/Nupky/webpack/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/ext
 @ ./~/mongoose/~/bson/~/bson-ext/ext/index.js 8:10-38
```

Any idea?

**Comment by sokra** [comment]
> Just forogt to add .node to the resolve.extensions array.

**Comment by georgiana-gligor** [comment]
I have the following:
```
  resolve: {
    extensions: ["", ".webpack.js", ".web.js", ".js", ".node"]
  }
```
in my `webpack.config.js` file, and unfortunately still get the same error.

**Comment by Sparragus** [comment]
@georgiana-gligor Did you `npm install node-loader` and included this on you module loaders?
```
            {
                test: /\.node$/,
                loader: "node-loader"
            }
```

**Comment by georgiana-gligor** [comment]
Yes, I do have that config for loading .node files

**Comment by Sparragus** [comment]
Can you please paste your errors using the `--display-error-details` flag on your webpack call?

**Comment by lai32290** [comment]
Thank you so much! This is helpful for me!

**Comment by lai32290** [comment]
I have the same problem in same situation, I'm creating a application using `Node Webkit`, where I using `Mongoose` for manipulate my `MongoDB`, and using `Webpack` for load my libraries and controllers.

I have installed `npm install node-loader` and set fallowing `webpack.config.js` configuration, but even with this configuration, is not working.

My `webpack.config.js`:

```javascript
var path = require("path");
module.exports = {
    entry: './view/main.js',
    output: {
        path: path.resolve(__dirname, "view"),
        filename: 'build.js'
    },
    module: {
        loaders: [
            { test: /\.vue$/, loader: 'vue' },
            { test: /\.node$/, loader: "node-loader" }
        ]
    },
    resolve: {
        extensions: ["", ".json", ".node", ".js"]
    },
    node: {
        net: "empty",
        tls: "empty",
    }
}
```

Result of my `webpack --display-error-details`:

```
C:\myProject>webpack --display-error-details
Hash: 6b5191967d482e5213d4
Version: webpack 1.12.8
Time: 8461ms
Asset    Size  Chunks             Chunk Names
build.js  2.6 MB       0  [emitted]  main
        [0] ./view/main.js 456 bytes {0} [built]
        [15] ./modules/products/controller.js 647 bytes {0} [built]
        [253] ./modules/products/model.js 174 bytes {0} [built]
        [254] ./modules/products/schema.js 279 bytes {0} [built]
        [256] ./modules/base/schema.js 161 bytes {0} [built]
+ 253 hidden modules

WARNING in ./~/mongoose/lib/drivers/index.js
Critical dependencies:
        8:11-74 the request of a dependency is an expression
@ ./~/mongoose/lib/drivers/index.js 8:11-74

WARNING in ./~/mongoose/lib/drivers/SPEC.md
Module parse failed: C:\myProject\node_modules\mongoose\lib\drivers\SPEC.md Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
|
| # Driver Spec
|
| TODO
@ ./~/mongoose/lib/drivers ^\.\/.*$

ERROR in ./~/mongodb/~/kerberos/lib/kerberos.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/kerberos in C:\myProject\node_modules\mongodb\n
ode_modules\kerberos\lib
resolve file
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory descrip
tion file)
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
@ ./~/mongodb/~/kerberos/lib/kerberos.js 1:15-51

ERROR in ./~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\myProject\node_modules\mon
godb\node_modules\kerberos\lib\win32\wrappers
resolve file
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory descrip
tion file)
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
        [C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
@ ./~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js 1:32-74

ERROR in ./~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\myProject\node_modules\mon
godb\node_modules\kerberos\lib\win32\wrappers
resolve file
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory descrip
tion file)
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
        [C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
@ ./~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js 1:28-70

ERROR in ./~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\myProject\node_modules\mon
godb\node_modules\kerberos\lib\win32\wrappers
resolve file
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory descrip
tion file)
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
        [C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
@ ./~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js 1:27-69

ERROR in ./~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\myProject\node_modules\mon
godb\node_modules\kerberos\lib\win32\wrappers
resolve file
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory descrip
tion file)
C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
        [C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\myProject\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
@ ./~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js 1:37-79
```

Where is error?

**Comment by Sparragus** [comment]
Try deleting `node_modules`, installing them again with `npm install`, and finally `webpack --display-error-details`.

**Comment by lai32290** [comment]
For realize this test, I created a new project, and install only `mongoose` and `node-loader`:
`npm install mongoose node-loader`

I create a `controller.js`, contains only one line:
`var mongoose require('mongoose');`

And my `main.js`, contains:
`var controller = require('./controller.js');`

This is my `webpack.config.js`:

```
var path = require("path");
module.exports = {
    entry: './main.js',
    output: {
        path: path.resolve(__dirname, "view"),
        filename: 'build.js'
    },
    module: {
        loaders: [
            { test: /\.node$/, loader: "node-loader" }
        ]
    },
    resolve: {
        extensions: ["", ".json", ".node", ".js"]
    },
    node: {
        net: "empty",
        tls: "empty",
    }
}
```

And fallowing the result of my `webpack --display-error-details`:

```
C:\Projects\Webpack>webpack --display-error-details
Hash: d6c04dfde7a59ff7c640
Version: webpack 1.12.9
Time: 2298ms
   Asset     Size  Chunks             Chunk Names
build.js  2.05 MB       0  [emitted]  main
   [0] ./main.js 44 bytes {0} [built]
   [1] ./controller.js 35 bytes {0} [built]
    + 219 hidden modules

WARNING in ./~/mongoose/lib/drivers/index.js
Critical dependencies:
8:11-74 the request of a dependency is an expression
 @ ./~/mongoose/lib/drivers/index.js 8:11-74

WARNING in ./~/mongoose/lib/drivers/SPEC.md
Module parse failed: C:\Projects\Webpack\node_modules\mongoose\lib\drivers\SPEC.md Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| 
| # Driver Spec
| 
| TODO
 @ ./~/mongoose/lib/drivers ^\.\/.*$

ERROR in ./~/mongoose/~/mongodb/lib/gridfs/grid_store.js
Module not found: Error: Cannot resolve module 'fs' in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\lib\gridfs
resolve module fs in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\lib\gridfs
  looking for modules in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules
    C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs doesn't exist (module as directory)
    resolve 'file' fs in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs.json doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs.node doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs.js doesn't exist
  looking for modules in C:\Projects\Webpack\node_modules\mongoose\node_modules
    C:\Projects\Webpack\node_modules\mongoose\node_modules\fs doesn't exist (module as directory)
    resolve 'file' fs in C:\Projects\Webpack\node_modules\mongoose\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.json doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.node doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.js doesn't exist
  looking for modules in C:\Projects\Webpack\node_modules
    C:\Projects\Webpack\node_modules\fs doesn't exist (module as directory)
    resolve 'file' fs in C:\Projects\Webpack\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\fs doesn't exist
        C:\Projects\Webpack\node_modules\fs.json doesn't exist
        C:\Projects\Webpack\node_modules\fs.node doesn't exist
        C:\Projects\Webpack\node_modules\fs.js doesn't exist
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\fs.js]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.js]
[C:\Projects\Webpack\node_modules\fs]
[C:\Projects\Webpack\node_modules\fs]
[C:\Projects\Webpack\node_modules\fs.json]
[C:\Projects\Webpack\node_modules\fs.node]
[C:\Projects\Webpack\node_modules\fs.js]
 @ ./~/mongoose/~/mongodb/lib/gridfs/grid_store.js 42:7-20

ERROR in ./~/mongoose/~/muri/lib/index.js
Module not found: Error: Cannot resolve module 'fs' in C:\Projects\Webpack\node_modules\mongoose\node_modules\muri\lib
resolve module fs in C:\Projects\Webpack\node_modules\mongoose\node_modules\muri\lib
  looking for modules in C:\Projects\Webpack\node_modules\mongoose\node_modules
    resolve 'file' fs in C:\Projects\Webpack\node_modules\mongoose\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.json doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.node doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.js doesn't exist
    C:\Projects\Webpack\node_modules\mongoose\node_modules\fs doesn't exist (module as directory)
  looking for modules in C:\Projects\Webpack\node_modules
    resolve 'file' fs in C:\Projects\Webpack\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\fs doesn't exist
        C:\Projects\Webpack\node_modules\fs.json doesn't exist
        C:\Projects\Webpack\node_modules\fs.node doesn't exist
        C:\Projects\Webpack\node_modules\fs.js doesn't exist
    C:\Projects\Webpack\node_modules\fs doesn't exist (module as directory)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs.js]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\fs]
[C:\Projects\Webpack\node_modules\fs]
[C:\Projects\Webpack\node_modules\fs.json]
[C:\Projects\Webpack\node_modules\fs.node]
[C:\Projects\Webpack\node_modules\fs.js]
[C:\Projects\Webpack\node_modules\fs]
 @ ./~/mongoose/~/muri/lib/index.js 234:2-15

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/kerberos.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_modules\m
ongodb\node_modules\kerberos\lib
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/kerberos.js 1:15-51

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js 1:28-70

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js 1:32-74

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js 1:27-69

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js 1:37-79
```

**Comment by Sparragus** [comment]
Is your app meant for the web? I'm starting to think it is an app that will run on node (not on the user's web client). 

Try adding `node` as the target (https://webpack.github.io/docs/configuration.html#target):

```js
// webpack.config.js
var path = require("path");
module.exports = {
    entry: './main.js',
    output: {
        path: path.resolve(__dirname, "view"),
        filename: 'build.js'
    },
    module: {
        loaders: [
            { test: /\.node$/, loader: "node-loader" }
        ]
    },
    resolve: {
        extensions: ["", ".json", ".node", ".js"]
    },
    node: {
        net: "empty",
        tls: "empty",
    },
    target: "node" // <---------- ADD THIS
}
```

Let me know how it goes.

**Comment by lai32290** [comment]
My app is for `Node-webkit`, so I tried set `target: "node"` and `target: "node-webkit"`
Fallowing error:

```
C:\Projects\Webpack>webpack --display-error-details
Hash: 5e37719f8355d0f0fb66
Version: webpack 1.12.9
Time: 2429ms
   Asset     Size  Chunks             Chunk Names
build.js  2.01 MB       0  [emitted]  main
   [0] ./main.js 44 bytes {0} [built]
   [1] ./controller.js 35 bytes {0} [built]
    + 227 hidden modules

WARNING in ./~/mongoose/lib/drivers/index.js
Critical dependencies:
8:11-74 the request of a dependency is an expression
 @ ./~/mongoose/lib/drivers/index.js 8:11-74

WARNING in ./~/mongoose/lib/drivers/SPEC.md
Module parse failed: C:\Projects\Webpack\node_modules\mongoose\lib\drivers\SPEC.md Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| 
| # Driver Spec
| 
| TODO
 @ ./~/mongoose/lib/drivers ^\.\/.*$

WARNING in ./~/mongoose/~/mongodb/~/es6-promise/dist/es6-promise.js
Module not found: Error: Cannot resolve module 'vertx' in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\es6-promise\d
ist
resolve module vertx in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\es6-promise\dist
  looking for modules in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules
    C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx doesn't exist (module as directory)
    resolve 'file' vertx in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.json doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.node doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.js doesn't exist
  looking for modules in C:\Projects\Webpack\node_modules\mongoose\node_modules
    C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx doesn't exist (module as directory)
    resolve 'file' vertx in C:\Projects\Webpack\node_modules\mongoose\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.json doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.node doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.js doesn't exist
  looking for modules in C:\Projects\Webpack\node_modules
    C:\Projects\Webpack\node_modules\vertx doesn't exist (module as directory)
    resolve 'file' vertx in C:\Projects\Webpack\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\vertx doesn't exist
        C:\Projects\Webpack\node_modules\vertx.json doesn't exist
        C:\Projects\Webpack\node_modules\vertx.node doesn't exist
        C:\Projects\Webpack\node_modules\vertx.js doesn't exist
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.js]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.js]
[C:\Projects\Webpack\node_modules\vertx]
[C:\Projects\Webpack\node_modules\vertx]
[C:\Projects\Webpack\node_modules\vertx.json]
[C:\Projects\Webpack\node_modules\vertx.node]
[C:\Projects\Webpack\node_modules\vertx.js]
 @ ./~/mongoose/~/mongodb/~/es6-promise/dist/es6-promise.js 125:20-30

ERROR in ./~/mongoose/package.json
Module parse failed: C:\Projects\Webpack\node_modules\mongoose\package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "mongoose",
|   "description": "Mongoose MongoDB ODM",
|   "version": "4.2.8",
 @ ./~/mongoose/lib/index.js 17:10-36

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/kerberos.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_modules\m
ongodb\node_modules\kerberos\lib
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/kerberos.js 1:15-51

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js 1:28-70

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js 1:27-69

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js 1:32-74

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_mod
ules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory
 description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file
)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js 1:37-79
```

**Comment by Sparragus** [comment]
*tl;dr: If you are using `npm 3`, make sure you got `kerberos` installed. Also, try adding the `json-loader`.*

I created the files you mention on https://github.com/webpack/webpack/issues/1040#issuecomment-160782253. I also did `npm install --save mongoose` and `npm install --save-dev node-loader`.

While mongoose was installing, I got this warning:
```
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

If you're using `npm 3+`, you will also need to `npm install --save kerberos` manually. Since many of the errors you have mention `kerberos`, let's check which version of `npm` you have installed. Check your version with `npm --version`. If the version is greater or equal to 3.0.0, then you will need to `npm install --save kerberos`.

(I'm still using `npm 2` so I didn't get `kerberos` related errors when I `webpack`.)

I then `webpack --display-error-details` and got one of the errors you got:
```
ERROR in ./~/mongoose/package.json
Module parse failed: C:\Projects\Webpack\node_modules\mongoose\package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "mongoose",
|   "description": "Mongoose MongoDB ODM",
|   "version": "4.2.8",
 @ ./~/mongoose/lib/index.js 17:10-36
```

The key line in that error is:
> You may need an appropriate **loader** to handle this **file type**.

In this case, it means you are missing a `json-loader`. To fix it `npm install --save-dev json-loader` and add the loader on your webpack.config.js.
```js
// webpack.config.js
loaders: [
     { test: /\.node$/, loader: "node-loader" },
     { test: /\.json$/, loader: "json-loader" }
]
```

Try `webpack --display-error-details` again. Did it work? (Hopefully it did! :D) If all goes well, you should see some warnings but no errors.

**Comment by lai32290** [comment]
I don't know if I'm make anything wrong, but is not success =/

My `npm --version` is `2.14.7`, and I installed `json-loader`, but is not success.

`webpack --display-error-details`:

```
$ webpack --display-error-details
Hash: 80d0f286fe099fb218f2
Version: webpack 1.12.8
Time: 1662ms
   Asset     Size  Chunks             Chunk Names
build.js  2.01 MB       0  [emitted]  main
   [0] ./main.js 44 bytes {0} [built]
   [1] ./controller.js 35 bytes {0} [built]
    + 227 hidden modules

WARNING in ./~/mongoose/lib/drivers/index.js
Critical dependencies:
8:11-74 the request of a dependency is an expression
 @ ./~/mongoose/lib/drivers/index.js 8:11-74

WARNING in ./~/mongoose/lib/drivers/SPEC.md
Module parse failed: C:\Projects\Webpack\node_modules\mongoose\lib\drivers\SPEC.md Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
|
| # Driver Spec
|
| TODO
 @ ./~/mongoose/lib/drivers ^\.\/.*$

WARNING in ./~/mongoose/~/mongodb/~/es6-promise/dist/es6-promise.js
Module not found: Error: Cannot resolve module 'vertx' in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\es6-promise\dist
resolve module vertx in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\es6-promise\dist
  looking for modules in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules
    C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx doesn't exist (module as directory)
    resolve 'file' vertx in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.json doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.node doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.js doesn't exist
  looking for modules in C:\Projects\Webpack\node_modules\mongoose\node_modules
    C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx doesn't exist (module as directory)
    resolve 'file' vertx in C:\Projects\Webpack\node_modules\mongoose\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.json doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.node doesn't exist
        C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.js doesn't exist
  looking for modules in C:\Projects\Webpack\node_modules
    C:\Projects\Webpack\node_modules\vertx doesn't exist (module as directory)
    resolve 'file' vertx in C:\Projects\Webpack\node_modules
      resolve file
        C:\Projects\Webpack\node_modules\vertx doesn't exist
        C:\Projects\Webpack\node_modules\vertx.json doesn't exist
        C:\Projects\Webpack\node_modules\vertx.node doesn't exist
        C:\Projects\Webpack\node_modules\vertx.js doesn't exist
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\vertx.js]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\vertx.js]
[C:\Projects\Webpack\node_modules\vertx]
[C:\Projects\Webpack\node_modules\vertx]
[C:\Projects\Webpack\node_modules\vertx.json]
[C:\Projects\Webpack\node_modules\vertx.node]
[C:\Projects\Webpack\node_modules\vertx.js]
 @ ./~/mongoose/~/mongodb/~/es6-promise/dist/es6-promise.js 125:20-30

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/kerberos.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\lib
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory description file)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/kerberos.js 1:15-51

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer.js 1:27-69

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js 1:37-79

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_context.js 1:28-70

ERROR in ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\lib\win32\wrappers
resolve file
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node doesn't exist
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js doesn't exist
resolve directory
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos\package.json doesn't exist (directory description file)
  C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos doesn't exist (directory default file)
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.json]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node]
[C:\Projects\Webpack\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.js]
 @ ./~/mongoose/~/mongodb/~/kerberos/lib/win32/wrappers/security_credentials.js 1:32-74
```

I'm using Windows 7  64 bits, maybe this make difference?

I has commit this test project in `github` to facilitate: [Project](https://github.com/lai32290/webpack_erro_example)

**Comment by Sparragus** [comment]
Something missing on Windows may be the issue. Try to [diagnose `kerberos` on Windows](https://github.com/christkv/kerberos#diagnosing-on-windows). Let us know if it works.

**Comment by croqaz** [comment]
Hello, I have the exact same issue on Ubuntu, using Node 4.2, Npm 3.5.

```
webpack 
Version: webpack 1.12.11
Time: 1808ms
    Asset     Size  Chunks             Chunk Names
js/app.js  3.77 MB       0  [emitted]  main
    + 451 hidden modules

WARNING in ./~/mongoose/lib/drivers/index.js
Critical dependencies:
8:11-74 the request of a dependency is an expression
 @ ./~/mongoose/lib/drivers/index.js 8:11-74

WARNING in ./~/mongoose/lib/drivers/SPEC.md
Module parse failed: /home/cro/Dev/akasha-electron/node_modules/mongoose/lib/drivers/SPEC.md Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| 
| # Driver Spec
| 
| TODO
 @ ./~/mongoose/lib/drivers ^\.\/.*$

WARNING in ./~/es6-promise/dist/es6-promise.js
Module not found: Error: Cannot resolve module 'vertx' in /home/cro/Dev/akasha-electron/node_modules/es6-promise/dist
 @ ./~/es6-promise/dist/es6-promise.js 132:20-30

WARNING in ./~/bson/lib/bson/index.js
Critical dependencies:
20:16-29 the request of a dependency is an expression
44:18-31 the request of a dependency is an expression
71:19-32 the request of a dependency is an expression
 @ ./~/bson/lib/bson/index.js 20:16-29 44:18-31 71:19-32

ERROR in ./~/kerberos/lib/kerberos.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/kerberos in /home/cro/Dev/akasha-electron/node_modules/kerberos/lib
 @ ./~/kerberos/lib/kerberos.js 1:15-51

ERROR in ./~/kerberos/lib/win32/wrappers/security_credentials.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /home/cro/Dev/akasha-electron/node_modules/kerberos/lib/win32/wrappers
 @ ./~/kerberos/lib/win32/wrappers/security_credentials.js 1:32-74

ERROR in ./~/kerberos/lib/win32/wrappers/security_context.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /home/cro/Dev/akasha-electron/node_modules/kerberos/lib/win32/wrappers
 @ ./~/kerberos/lib/win32/wrappers/security_context.js 1:28-70

ERROR in ./~/kerberos/lib/win32/wrappers/security_buffer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /home/cro/Dev/akasha-electron/node_modules/kerberos/lib/win32/wrappers
 @ ./~/kerberos/lib/win32/wrappers/security_buffer.js 1:27-69

ERROR in ./~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build/Release/kerberos in /home/cro/Dev/akasha-electron/node_modules/kerberos/lib/win32/wrappers
 @ ./~/kerberos/lib/win32/wrappers/security_buffer_descriptor.js 1:37-79
```

Tried all kinds of configurations...

**Comment by Sparragus** [comment]
Please post your `webpack.config.js` and `package.json`so we can take a look a it. I wonder why this is happening to so many people...

**Comment by croqaz** [comment]
Found the problem !!
The "kerberos" dependency was not installed correctly. I tried to require the module by hand and I couldn't.
I tried to install it and i had error from https://github.com/christkv/kerberos/issues/21 ;
I installed "libkrb5-dev", then installed "kerberos" again and now mongoose works with just 1 warning:

```
WARNING in ./~/mongoose/lib/drivers/index.js
Critical dependencies:
8:11-74 the request of a dependency is an expression
 @ ./~/mongoose/lib/drivers/index.js 8:11-74

WARNING in ./~/mongoose/lib/drivers/SPEC.md
Module parse failed: /home/cro/Dev/akasha-electron/node_modules/mongoose/lib/drivers/SPEC.md Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| 
| # Driver Spec
| 
| TODO
 @ ./~/mongoose/lib/drivers ^\.\/.*$
```

**Comment by mxklabs** [comment]
I'm not sure how helpful this is to anybody but I've been stuck on this issue (web-packing mongoose) for some time and came up with a resolution I've not seen mentioned here, so I thought I'd share it.

The primary issue I've been stuck on  is web-packing muri, a dependency of mongoose. This is because  `node_modules/muri/lib/index.js` reads muri's `package.json` in order to populate a version number:

```
require('fs').readFileSync(__dirname + '/../package.json', 'utf8')
```

The reason this was a problem for me is that after webpack does its business the resulting javascript file still wants to read muri's `package.json` but fails miserably.

I've resolved this by using a browserify webpack loader (brfs) which embeds files read by the fs module into the code. For details on how to use this in webpack read [this](https://github.com/webpack-contrib/transform-loader).

Note that the following rule helped me successfully pack muri:
```
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "transform-loader?brfs",
        include: path.resolve(__dirname, "node_modules/muri/lib/index.js")
      }
   ]
}
```

I hope this is useful to someone!
