### ISSUE TITLE
Multiple targets

### ISSUE THREAD

**Issue by jussi-kalliokoski** [webpack/webpack#1122]
This is mostly to open discussion on how to solve a specific problem at this point, I only have a crude idea in my head of how this could be made to work.

I currently have an isomorphic website ([www.toons.tv](https://www.toons.tv)) that's built using React and Webpack on both the server and the client. The current build setup is quite clunky and accounts for a big portion of code in the whole project - the main reason for this is that in order to have an efficient development setup, I of course want to be watching all the assets and rebuild them when changed. However, every time the assets are rebuilt, the JS (both client and server) needs to know the new asset URLs. This means a very complex setup where webpack is only building the JS, and the rest (icon fonts, web fonts, images and other assets) is handled by gulp, and then all these update a `build-manifest.json` file that is required by the JS, so that the webpack builds are triggered as well.

I'd like to move the asset pipeline completely to webpack instead, but this is problematic because currently you can only have one target (and set of options) per compiler, so the assets would be rebuilt twice and given that some of the assets are not generated deterministically (e.g. the icon fonts), the client could end up with different asset URLs than the server, which could easily lead to resources being loaded twice on the client.

At some point, I would also like to take service workers into use, and the worker would also need the same asset URLs.

One proposal that comes to mind is that you could define per-entry options:

``` javascript
webpack({
  entry: {
    client: {
      entry: "/path/to/client/entry.js",
      target: "browser",
    },
    server: {
      entry: "/path/to/server/entry.js",
      target: "node",
    },
  },
});
```

I do realize that this would probably be a pain to implement, especially if the different entries are supposed to share parts of the pipeline while diverging at some points (e.g. if there's different plugins and/or loaders used by different entries), and also possibly require breaking changes to the plugin API, but I do hope to see this use case solved by webpack at some point.

Cheers! :heart: :sparkles:

**Comment by anyong** [comment]
Yeah I wish there was a better way to do this too. I'm currently running multiple webpack configurations in gulp tasks, but just today for some reason or other this stopped working and webpack won't watch my files anymore.

**Comment by sokra** [comment]
You can pass an array of configurations to webpack (with different targets). This works fine.

> that some of the assets are not generated deterministically (e.g. the icon fonts)

Make sure they are determinisitic. It's a guideline for loaders.

``` js
webpack([
    {
      name: "client",
      entry: "/path/to/client/entry.js",
      target: "browser",
    },
    {
      name: "server",
      entry: "/path/to/server/entry.js",
      target: "node",
    },
]);
```

**Comment by jussi-kalliokoski** [comment]
> You can pass an array of configurations to webpack (with different targets). This works fine.

Does that have some way to refer the client JS file from the server (in order to put it in a script tag)?

**Comment by garaboncias** [comment]
+1
array of configuration is not optimal because "browser" and "webworker" could share bundles, but with multiply configuration they do not share anything.
i think webpack should unify "browser" and "webworker" target or the second best solution is that target should be configured by entry points.
This should be essential because usualy webworker share a lot of common library with the main thread, and browser could use the cache.

**Comment by Dharmoslap** [comment]
@sokra but how can I pass array of configurations to webpack, if I'm using a config file?
Let's say I have something like this:

```
module.exports = {
    entry: {
         client: "./client.js",
        server: "./server.js",
    },
    output: {
        path: __dirname + '/__build__',
        filename: '[name].js'"
    },
    module: {
        loaders: [
            { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader' }
        ]
    }
};
```

How to make multiple targets working here?

**Comment by andreypopp** [comment]
@Dharmoslap did you try: `module.exports = [{...}, {...}];`?

**Comment by Dharmoslap** [comment]
@andreypopp works!

**Comment by omerts** [comment]
If your config file is big, and all you need is to change the target for a specific entry, its lengthy and has duplicate configuration for no reason. 

I too would love to see:
```javascript
webpack({
  entry: {
    client: {
      entry: "/path/to/client/entry.js",
      target: "browser",
    },
    server: {
      entry: "/path/to/server/entry.js",
      target: "node",
    },
  },
});
```

**Comment by Pfeifenjoy** [comment]
Actually this is can be solved via using two configs as explained here:
https://stackoverflow.com/questions/37788142/webpack-for-back-end/37920356#37920356

**Comment by BabakMN** [comment]
@Pfeifenjoy that takes you most of the way there however there's still a subtle annoying problem that remains which is that you can't reference or include the script from the client bundle inside the server bundle (which is very handy for full isomorphic application use case).

**Comment by Pfeifenjoy** [comment]
@BabakMN why can't you do that?

**Comment by BabakMN** [comment]
@Pfeifenjoy as far as I know there's no way to reference an asset across two compilations like that.

The use case of it for example is when your client configuration produces some scripts and css files or an index.html file and it would be nice to be able to require the index.html that was just built in the client compilation inside the server bundle.

**Comment by Pfeifenjoy** [comment]
@BabakMN can't you just require the source of it.
e.g.:
I have an App Component and a server script in a folder structure like this:

```
app/
    App.js
    index.js
server/
    index.js
```

The app is the main react Component and the index.js is the entry point for the client bundle.
Than I can just require the App.js in the server/index.js:

`require("../app/App")`

In the server configuration webpack would have to bundle every resources as base64 encoding into one file which should not cause any problems, because it does'nt need to be downloaded from the client and therefore the file can be bigger than the client bundle.

In the client configuration you can exclude resources like vendor files or images.
These can be than served statically via your server.

Yes, than it will be bundled the client resources twice, but this overhead should not be too bad.

Please tell me if I understood your problem correctly.

**Comment by Pfeifenjoy** [comment]
@BabakMN 
I just got your point and yes this cannot be solved easily. 
Maybe their is a chance to generate the assets of the client and put them all into one public directory.
Than it might be possible to have a loader which generates a relative url to the according asset.

**Comment by BabakMN** [comment]
@Pfeifenjoy you may find the following issues interesting: #2309 #2270

I have been experimenting with some relatively crazy setups of a proxy server that uses webpack with a memory file system and as the server bundle gets built it spawns a fresh node process, pipes the server bundle into it and puts it into service as the upstream of the reverse http proxy.

My aim is to achieve a better developer experience in a fully isomorphic context.

**Comment by sokra** [comment]
This is an old issue. I guess the problem was solved in the meantime. If not please open a new issue.

**Comment by omeid** [comment]
> I guess the problem was solved in the meantime.
Why guess? the problem is still not solved.

**Comment by hinell** [comment]
@omeid It is rather not a problem but a suggestion I believe. 
@sokra I would like to ask you: does webpack shares common chunks between separate configurations when two and more configuration objects are used?
I think if two compilers don't share them it leads to additional overhead and decrease overall performance and productivity.

**Comment by rjgotten** [comment]
@hinell 
It shouldn't be forced to share chunks. More often than not the separate configurations and separate compilations are separate for a _reason_.  E.g. when you are multi-targeting old browsers and new browsers with separate builds. In this scenario IE11 would need a fully polyfilled build using `babel-loader` with `preset-env` transforming everything to include CoreJS polyfills, while modern browsers wouldn't. Those builds shouldn't share chunks. Ever.

**Comment by hinell** [comment]
@rjgotten Now, 8 month later after I've left my question we still don't know yet whether compiler handles similar packages separately or not. There definitely cases where such behavior is unwanted. But in case of similar packages (with similar versions) I think it's more than wanted for performance reasons.

**Comment by Sominemo** [comment]
Five years passed already, that's a shame.

**Comment by evilebottnawi** [comment]
> Five years passed already, that's a shame.

Nice to hear thanks for the work done.

Solved in webpack@5

**Comment by EECOLOR** [comment]
@alexander-akait Could you give a bit more detail on how it is solved?

**Comment by rjgotten** [comment]
> @EECOLOR 
> Could you give a bit more detail on how it is solved?

The cheeky answer is probably: module federation. If you have module chunks that should be shared across build configurations, that's definitely one way of doing it.

**Comment by 4127157** [comment]
As of webpack 5 is it possible to have different targets per entry in the fashion listed below? Sorry, the thread did not make it clear to me whether it was implemented or not. 

```
webpack({
  entry: {
    client: {
      entry: "/path/to/client/entry.js",
      target: "browser",
    },
    server: {
      entry: "/path/to/server/entry.js",
      target: "node",
    },
  },
});
```
