### ISSUE TITLE
[5.1.2] No longer the very useful colored tabular stats in webpack 5

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#11716]
# Bug report

In webpack 4 the stats looked like this
![image](https://user-images.githubusercontent.com/1009585/96218753-ab10bd00-0f85-11eb-94bf-e2a5c78ffc85.png)

and in webpack 5 it looks like this:
![image](https://user-images.githubusercontent.com/1009585/96218836-dd221f00-0f85-11eb-9c6a-42cc13081306.png)

I'm using the following unchanged `stat` configuration and was wondering how to get back the very helpful tabular output in version 4. I also noticed, that the output no longer seems to be colored.

```js
{
	all: undefined,
	assets: true,
	assetsSort: 'field',
	cached: false,
	children: false,
	chunks: false,
	chunkModules: false,
	chunkOrigins: false,
	chunksSort: 'field',
	colors: true,
	errors: true,
	errorDetails: true,
	excludeAssets: assetName => !/\.js$/i.test(assetName),
	hash: false,
	modules: false,
	modulesSort: 'field',
	publicPath: false,
	reasons: false,
	source: false,
	timings: true,
	version: true,
	warnings: true
}
```

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.1.2
Node.js version: 14.13.0
Operating System: 10.15.7
Additional tools:

**Comment by sokra** [comment]
> I also noticed, that the output no longer seems to be colored.

That's a bug in the current cli. As workaround you can add `--stats-colors` or `stats.colors: true`

**Comment by doberkofler** [comment]
I already use `stats.colors: true` but it does not seem to make any difference.

**Comment by evilebottnawi** [comment]
Fixed in master, release will be today

**Comment by doberkofler** [comment]
So the stats will look like the ones in webpack 4 or is this only related to the color?

**Comment by evilebottnawi** [comment]
stats in webpack@4 and webpack@5 is different, yes it will be colored

**Comment by doberkofler** [comment]
I understand that they are different but this is what this SR is about as I found the stats in webpack 4 a lot more readable if you look at my screenshots.

**Comment by evilebottnawi** [comment]
@doberkofler it was described in changelog, we change it to reduce memory usage and do it better, feel free to use options to setup them as you want

**Comment by doberkofler** [comment]
I understand that this minor issue and (clearly) I already tried (quite a bit) to change the options but (and I might be wrong) nothing shows the results in the nicely (each asset with it's size in a line and colored if big) combined tabular way it was shown in webpack 4.
If I missed something, please be so kind and point me into the right direction to get "something" like the tabular output in webpack 4.

**Comment by evilebottnawi** [comment]
What you want to see?

**Comment by sokra** [comment]
Since webpack 5 you can write plugins for the stats output. If you have an idea for a better way to display it, you can do that in a plugin.

**Comment by doberkofler** [comment]
This is what I found very helpful in a projects with a large number of assets:

1) A table of the generated assets
![image](https://user-images.githubusercontent.com/1009585/96254752-170b1980-0fb6-11eb-9350-ed0612351c2a.png)

2) A table of the entry points and the dependencies
![image](https://user-images.githubusercontent.com/1009585/96254854-46ba2180-0fb6-11eb-81d3-d9a6b2c9a204.png)

**Comment by evilebottnawi** [comment]
@doberkofler sorry, it was changed to avoid extra large wide, https://github.com/webpack/webpack/issues/11716#issuecomment-709996506

**Comment by doberkofler** [comment]
@evilebottnawi I think the intention of my original bug report got somehow lost in the overall discussion.
My main concern is not the formatting or coloring of the output but rather the content itself that does not contain any of the expected key information.

This is all of the output from webpack 5 without any `stats` property:
```
assets by path *.png 827 KiB 212 assets
assets by path imgs/ 12.7 KiB 70 assets
assets by path tinymce/ 803 KiB 42 assets
assets by path *.gif 91.2 KiB 34 assets
assets by status 24.5 MiB [emitted] 21 assets
assets by path filetypes/*.png 77.4 KiB 12 assets
assets by chunk 39 KiB (name: uirichtextedit) 2 assets
assets by path *.jpg 9.34 KiB
  asset iconsprite2.jpg 7.92 KiB [compared for emit] [copied]
  asset form_btn_select.jpg 1.42 KiB [compared for emit]
assets by path *.ico 5.06 KiB
  asset magnifier.ico 4.19 KiB [compared for emit] [copied]
  asset favicon.ico 894 bytes [compared for emit] [copied]
asset vendors-node_modules_tinymce_icons_default_index_js-node_modules_tinymce_plugins_advlist_inde-0682fb.js 7.36 MiB [compared for emit] (id hint: vendors)
asset tinymce_editor.css 670 bytes [compared for emit] [copied]
orphan modules 1.78 MiB [orphan] 966 modules
runtime modules 46 KiB 76 modules
code generated modules 8.62 MiB (javascript) 310 KiB (css/mini-extract) [code generated]
  modules by path ./node_modules/ 6.35 MiB (javascript) 42.9 KiB (css/mini-extract)
    javascript modules 6.29 MiB 531 modules
    json modules 62.9 KiB 9 modules
    css modules 42.9 KiB 4 modules
  modules by path ./src/ 712 KiB (javascript) 147 KiB (css/mini-extract)
    cacheable modules 712 KiB 152 modules
    css modules 147 KiB 43 modules
  modules by path ./vendor/ 1.57 MiB (javascript) 120 KiB (css/mini-extract)
    cacheable modules 1.57 MiB
      modules by path ./vendor/dhtmlx-grid/v5/*.js 1.02 MiB 2 modules
    css modules 120 KiB 7 modules
  readable-stream (ignored) 15 bytes [built] [code generated]
webpack 5.1.3 compiled successfully in 10563 ms
```

and this was the output in webpack 4:
```
                               Asset      Size  Chunks                    Chunk Names
                 tinymce/langs/de.js  13.8 KiB          [emitted]         
        tst_examples_dropzone.min.js  76.1 KiB       1  [emitted]         tst_examples_dropzone
      tst_examples_exceptions.min.js  76.1 KiB       2  [emitted]         tst_examples_exceptions
      tst_examples_fileupload.min.js  75.3 KiB       3  [emitted]         tst_examples_fileupload
      tst_examples_jsonstatus.min.js  76.2 KiB       4  [emitted]         tst_examples_jsonstatus
         tst_examples_loading.min.js  75.8 KiB       5  [emitted]         tst_examples_loading
        tst_examples_uidialog.min.js  81.9 KiB       6  [emitted]         tst_examples_uidialog
          tst_examples_uiform.min.js  79.2 KiB       7  [emitted]         tst_examples_uiform
tst_examples_uimultipleselect.min.js  76.5 KiB       8  [emitted]         tst_examples_uimultipleselect
tst_examples_uirichtexteditor.min.js  77.3 KiB       9  [emitted]         tst_examples_uirichtexteditor
         tst_examples_uitable.min.js  1.28 MiB      10  [emitted]  [big]  tst_examples_uitable
         tst_examples_vendors.min.js  1.33 MiB       0  [emitted]  [big]  tst_examples_vendors
               uirichtextedit.min.js  3.22 KiB      11  [emitted]         uirichtextedit
       vendors~uirichtextedit.min.js  1.11 MiB      12  [emitted]  [big]  vendors~uirichtextedit
 + 409 hidden assets
Entrypoint tst_examples_dropzone [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_dropzone.min.css tst_examples_dropzone.min.js tst_examples_dropzone.min.css.map tst_examples_dropzone.min.js.map
Entrypoint tst_examples_exceptions [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_exceptions.min.css tst_examples_exceptions.min.js tst_examples_exceptions.min.css.map tst_examples_exceptions.min.js.map
Entrypoint tst_examples_fileupload [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_fileupload.min.css tst_examples_fileupload.min.js tst_examples_fileupload.min.css.map tst_examples_fileupload.min.js.map
Entrypoint tst_examples_jsonstatus [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_jsonstatus.min.css tst_examples_jsonstatus.min.js tst_examples_jsonstatus.min.css.map tst_examples_jsonstatus.min.js.map
Entrypoint tst_examples_loading [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_loading.min.css tst_examples_loading.min.js tst_examples_loading.min.css.map tst_examples_loading.min.js.map
Entrypoint tst_examples_uidialog [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_uidialog.min.css tst_examples_uidialog.min.js tst_examples_uidialog.min.css.map tst_examples_uidialog.min.js.map
Entrypoint tst_examples_uiform [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_uiform.min.css tst_examples_uiform.min.js tst_examples_uiform.min.css.map tst_examples_uiform.min.js.map
Entrypoint tst_examples_uimultipleselect [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_uimultipleselect.min.css tst_examples_uimultipleselect.min.js tst_examples_uimultipleselect.min.css.map tst_examples_uimultipleselect.min.js.map
Entrypoint tst_examples_uirichtexteditor [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_uirichtexteditor.min.css tst_examples_uirichtexteditor.min.js tst_examples_uirichtexteditor.min.css.map tst_examples_uirichtexteditor.min.js.map
Entrypoint tst_examples_uitable [big] = tst_examples_vendors.min.js tst_examples_vendors.min.js.map tst_examples_uitable.min.css tst_examples_uitable.min.js tst_examples_uitable.min.css.map tst_examples_uitable.min.js.map
```

I miss all of my assets and all of my entry points in the output of webpack 5 and despite on what i change in the `stats` option, the output does not really change at all.

This is the (cleaned up) actual configuration object return from my webpack.config.js
```js
[
  {
    mode: 'development',
    entry: {
      tst_examples_dropzone: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_dropzone/index.ts'
      ],
      tst_examples_exceptions: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_exceptions/index.ts'
      ],
      tst_examples_fileupload: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_fileupload/index.ts'
      ],
      tst_examples_jsonstatus: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_jsonstatus/index.ts'
      ],
      tst_examples_loading: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_loading/index.ts'
      ],
      tst_examples_uidialog: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_UiDialog/index.ts'
      ],
      tst_examples_uiform: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_UiForm/index.ts'
      ],
      tst_examples_uimultipleselect: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_UiMultipleSelect/index.ts'
      ],
      tst_examples_uirichtexteditor: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_UiRichTextEditor/index.ts'
      ],
      tst_examples_uitable: [
        '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/examples/tst_examples_UiTable/index.ts'
      ]
    },
    output: {
      path: '/Users/doberkofler/ords/doc_root/lj_unittest',
      filename: '[name].js',
      chunkFilename: '[name].js',
      publicPath: ''
    },
    module: {
      rules: [
        {
          test: '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/jquery/dist/jquery.js',
          loader: 'expose-loader',
          options: { exposes: [ '$', 'jQuery' ] }
        },
        {
          test: /.tsx?$/i,
          exclude: [ /vendor/, /node_modules/ ],
          use: [
            { loader: 'ts-loader', options: { transpileOnly: true } },
            {
              loader: 'ifdef-loader',
              options: { 'ifdef-verbose': false, DEBUG: true, TEST_MODE: false }
            }
          ]
        },
        {
          test: /\.styl$/i,
          include: [ /src/ ],
          use: [
            '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/mini-css-extract-plugin/dist/loader.js',
            {
              loader: 'css-loader',
              options: { sourceMap: false, importLoaders: 2 }
            },
            {
              loader: 'postcss-loader',
              options: {
                postcssOptions: {
                  sourceMap: false,
                  plugins: [
                    {
                      postcssPlugin: 'autoprefixer',
                      prepare: [Function: prepare],
                      info: [Function: info],
                      options: {},
                      browsers: undefined
                    }
                  ]
                }
              }
            },
            { loader: 'stylus-loader', options: { sourceMap: false } }
          ]
        },
        {
          test: /\.s[ac]ss$/i,
          include: [ /src/ ],
          use: [
            '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/mini-css-extract-plugin/dist/loader.js',
            {
              loader: 'css-loader',
              options: { sourceMap: false, importLoaders: 2 }
            },
            {
              loader: 'postcss-loader',
              options: {
                postcssOptions: {
                  sourceMap: false,
                  plugins: [
                    {
                      postcssPlugin: 'autoprefixer',
                      prepare: [Function: prepare],
                      info: [Function: info],
                      options: {},
                      browsers: undefined
                    }
                  ]
                }
              }
            },
            { loader: 'sass-loader', options: { sourceMap: false } }
          ]
        },
        {
          test: /\.css$/i,
          include: [ /src/ ],
          use: [
            '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/mini-css-extract-plugin/dist/loader.js',
            {
              loader: 'css-loader',
              options: { sourceMap: false, importLoaders: 1 }
            },
            {
              loader: 'postcss-loader',
              options: {
                postcssOptions: {
                  sourceMap: false,
                  plugins: [
                    {
                      postcssPlugin: 'autoprefixer',
                      prepare: [Function: prepare],
                      info: [Function: info],
                      options: {},
                      browsers: undefined
                    }
                  ]
                }
              }
            }
          ]
        },
        {
          test: /\.(png|gif|jpe?g|svg|ico)$/i,
          include: [ /img/, /src/, /vendor/, /node_modules/ ],
          use: [
            {
              loader: 'file-loader',
              options: { name: '[name].[ext]' }
            }
          ]
        },
        {
          test: /\.html$/i,
          loader: 'html-loader',
          options: { attributes: false }
        },
        { test: /\.m?js$/, resolve: { fullySpecified: false } }
      ]
    },
    resolve: {
      extensions: [ '.ts', '.tsx', '.js', '.jsx' ],
      alias: {
		/* ... */
      }
    },
    plugins: [
      ProvidePlugin {
        definitions: { '$': 'jquery', jQuery: 'jquery' }
      },
      ImageminPlugin {
        options: {
          disable: true,
          maxConcurrency: 8,
          imageminOptions: {
            plugins: [
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)]
            ]
          },
          testFunction: [Function (anonymous)],
          externalImages: {
            context: '.',
            sources: [],
            destination: '.',
            fileName: null
          },
          cacheFolder: null
        }
      },
      DefinePlugin {
        definitions: {
          __VERSION__: '"200900"',
          __REACT_DEVTOOLS_GLOBAL_HOOK__: '({isDisabled: true})',
          __REVISION__: '61557',
          __TEST_MODE__: 'false'
        }
      },
      MiniCssExtractPlugin {
        options: {
          filename: '[name].css',
          ignoreOrder: false,
          chunkFilename: '[name].css'
        }
      },
      ProgressPlugin {
        profile: false,
        handler: undefined,
        modulesCount: 5000,
        dependenciesCount: 10000,
        showEntries: true,
        showModules: true,
        showDependencies: true,
        showActiveModules: true,
        percentBy: undefined
      }
    ],
    optimization: {
      splitChunks: {
        cacheGroups: {
          commons: {
            test: /\.(js|jsx|ts|tsx)$/i,
            name: 'tst_examples_vendors',
            chunks: 'all',
            minChunks: 2
          }
        }
      },
      emitOnErrors: false,
      minimizer: [
        TerserPlugin {
          options: {
            test: /\.[cm]?js(\?.*)?$/i,
            extractComments: false,
            cache: true,
            cacheKeys: [Function: cacheKeys],
            parallel: true,
            include: undefined,
            exclude: undefined,
            minify: undefined,
            terserOptions: { output: { comments: /@preserve/i } }
          }
        }
      ]
    },
    devtool: 'eval-source-map'
  }
]
```

**Comment by sokra** [comment]
Webpack 5 avoids spammy stats output by default. So if you have a lot of something it's probably hidden by default. All things have limits, but you can remove them.

If you want to see more about your assets increase the space allocated for assets e. g. with `stats.assetsSpace: Infinity`.
If you want to see the entrypoints `stats.entrypoints: true`. `chunkGroupMaxAssets: Infinity` is also useful if your entrypoints have a lot assets.

There is also a preset like `stats.preset: "verbose"`.
You can use all options via CLI if you only want to show that info temporary.

**Comment by sokra** [comment]
Not sure why non of your changes have an effect. Maybe that's a bug. If you can't figure that out, please provide a repro.

**Comment by doberkofler** [comment]
This is the (same) output with ` stats: { preset: 'verbose' }`:

```
assets by path *.png 827 KiB 212 assets
assets by path imgs/ 12.7 KiB 70 assets
assets by path tinymce/ 803 KiB 42 assets
assets by path *.gif 91.2 KiB 34 assets
assets by status 24.5 MiB [emitted] 21 assets
assets by path filetypes/*.png 77.4 KiB 12 assets
assets by chunk 39 KiB (name: uirichtextedit) 2 assets
assets by path *.jpg 9.34 KiB
  asset iconsprite2.jpg 7.92 KiB [compared for emit] [copied]
  asset form_btn_select.jpg 1.42 KiB [compared for emit]
assets by path *.ico 5.06 KiB
  asset magnifier.ico 4.19 KiB [compared for emit] [copied]
  asset favicon.ico 894 bytes [compared for emit] [copied]
asset vendors-node_modules_tinymce_icons_default_index_js-node_modules_tinymce_plugins_advlist_inde-0682fb.js 7.36 MiB [compared for emit] (id hint: vendors)
asset tinymce_editor.css 670 bytes [compared for emit] [copied]
orphan modules 1.78 MiB [orphan] 966 modules
runtime modules 46 KiB 76 modules
code generated modules 8.62 MiB (javascript) 310 KiB (css/mini-extract) [code generated]
  modules by path ./node_modules/ 6.35 MiB (javascript) 42.9 KiB (css/mini-extract)
    javascript modules 6.29 MiB 531 modules
    json modules 62.9 KiB 9 modules
    css modules 42.9 KiB 4 modules
  modules by path ./src/ 712 KiB (javascript) 147 KiB (css/mini-extract)
    cacheable modules 712 KiB 152 modules
    css modules 147 KiB 43 modules
  modules by path ./vendor/ 1.57 MiB (javascript) 120 KiB (css/mini-extract)
    cacheable modules 1.57 MiB
      modules by path ./vendor/dhtmlx-grid/v5/*.js 1.02 MiB 2 modules
    css modules 120 KiB 7 modules
  readable-stream (ignored) 15 bytes [built] [code generated]
webpack 5.1.3 compiled successfully in 10890 ms
```

**Comment by sokra** [comment]
Which webpack-cli?

**Comment by doberkofler** [comment]
webpack-cli 4.0.0

**Comment by doberkofler** [comment]
It took me quite a bit but I think I now have something that might explain the problem.
The output seems to change when only using a single configuration instead of multiple.

This form show the mangled output:
```js
module.exports = function (env, options) {
   return [{...}];
};
```

and this form shows the expected one:
```js
module.exports = function (env, options) {
   return {...};
};
```

**Comment by doberkofler** [comment]
I probably did not make myself very clear.
Using `stats: { preset: 'verbose' }` has no effect when using an array of configuration objects but does work when using a single configuration object.

**Comment by sokra** [comment]
That seem to be a webpack-cli issue

**Comment by doberkofler** [comment]
As this seems to be a bug: will you reopen this SR or do I have to file a new one?

**Comment by evilebottnawi** [comment]
fixed in master, release will be today

**Comment by doberkofler** [comment]
@evilebottnawi I guess it has not yet been released but will this fix both bugs?
1) the important problem when using multiple configurations
2) the small bug with the missing colors

**Comment by doberkofler** [comment]
@evilebottnawi Excellent. This is now working. Thank you and keep up the good work.

**Comment by tianxiemaochiyu** [comment]
@doberkofler  Has this error been fixed? This problem still exists in webpack@5.4.0.

<img width="1267" alt="截屏2020-11-11 下午4 36 41" src="https://user-images.githubusercontent.com/16790771/98788586-15f5cc80-243c-11eb-98b9-bd71841bc52f.png">

**Comment by doberkofler** [comment]
@oles I personally preferred the webpack 4 output and currently use the following settings in webpack 5

```js
		stats: {
			all: undefined,
			assets: true,
			excludeAssets: assetName => !/\.js$/i.test(assetName),
			assetsSort: 'name',
			chunks: false,
			entrypoints: true,
			assetsSpace: Number.MAX_SAFE_INTEGER,
			moduleAssets: false,
			groupAssetsByChunk: false,
			groupAssetsByEmitStatus: false,
			groupAssetsByInfo: false,
			groupModulesByAttributes: false,
			warnings: true,
			errors: true,
			errorDetails: true,
		},
```

**Comment by oles** [comment]
Thank you for that.

Sadly it only changed a word in my output: "asset" to "hidden"

Sad to see the nice table overview of the sizes of the assets gone.
Was useful to quickly skim over the sizes row to see if something was wrong.

Now it's quick to miss if something got unexpectedly big:
![Screenshot from 2021-04-19 22-44-40](https://user-images.githubusercontent.com/7634050/115301024-f7210200-a160-11eb-8d1f-36bcd14ee088.png)

**Comment by oles** [comment]
vs this (not the same project, but a little similar):

![Screenshot from 2021-04-19 22-46-45](https://user-images.githubusercontent.com/7634050/115301259-3cddca80-a161-11eb-953f-4e01dc67f1c9.png)

The new one works, but feels like a step back - at least for simple configs. Perhaps the new one works better across all different types of configurations, while the old one did not scale well on advanced configs.

Any thoughts on this, @alexander-akait?

Apart from this, the migration from v4 to v5 was very smooth - thank you! :clap:

**Comment by alexander-akait** [comment]
@oles Do you need only assets? What is current your value of stats?

**Comment by oles** [comment]
@alexander-akait The most important thing for me is to verify that all the chunks and assets are a reasonable and expected file size.

**Comment by oles** [comment]
Indeed, I'll consider it for a hobby project! Thank you again for you work :v:

**Comment by MtDalPizzol** [comment]
Sorry for commenting on a closed issue, but I just spent an entire afternoon trying to get the tabular assets to show up in Webpack 5 stats output  just to find this discussion today. Was anyone able to get that table back into Webpack 5? Is there any plugins for that?

IMO, the tabular assets from webpack 4 was waaaay clearer to visualize the structure of the output, specially when using the devserver and files are not written to disk but you need to see where they are located.

I have a use case where I only use Webpack for bundling JS and CSS without generating any HTML automatically, so I need to know exactly where the resulting files are located so I can generate the proper `link` and `script` manually. That table was extremely helpful for that.

**Comment by thjiang** [comment]
> Thanks for the tip, @RiZKiT - indeed, it does!
> 
> I'm still missing the tabular view as shown [here](https://github.com/webpack/webpack/issues/11716#issuecomment-822779870) though!

I also encountered the same problem, I wrote a plugin to format the output of webpack5, maybe you can refer to it.

https://github.com/LeMeridien/webpack-stats-prettify-plugin

![https://github.com/LeMeridien/webpack-stats-prettify-plugin/raw/master/assets/after.png](https://github.com/LeMeridien/webpack-stats-prettify-plugin/raw/master/assets/after.png)
