### ISSUE TITLE
runtime chunk content is different from build to build, but source code has not changed

### ISSUE THREAD

**Issue by rifler** [webpack/webpack#12784]
# Bug report

**What is the current behavior?**
When I run two builds from the same git commit hash on different linux machines - it provides me almost the same output, except runtime chunk

Example:
```
// first run on machine_1 in CI
runtime.29356d8efe45cd19.bundle.ru.js
metrika.6dc696f23ae55bfc.bundle.css
metrika.94f2d9bc1bb519d8.bundle.ru.js
vendor.8c9ddbe5319ab05b.bundle.css
vendor.661550bb09edd434.bundle.ru.js
touch.39e720bafce5952c.bundle.css
touch.4c907c11d1c25525.bundle.ru.js

// second run on machine_2 in CI
runtime.af9dee425cfdb58c.bundle.ru.js
metrika.6dc696f23ae55bfc.bundle.css
metrika.94f2d9bc1bb519d8.bundle.ru.js
vendor.8c9ddbe5319ab05b.bundle.css
vendor.661550bb09edd434.bundle.ru.js
touch.39e720bafce5952c.bundle.css
touch.4c907c11d1c25525.bundle.ru.js
```

As you can see, all hashes are the same, except runtime.

But they don't differ significantly:
https://www.diffchecker.com/Szw487ot

just two variables swap their names - `l` to `f` and `f` to `l`

**If the current behavior is a bug, please provide the steps to reproduce.**
config:
```js
{
    mode: 'production',
    optimization: {
        runtimeChunk: 'single',
        removeAvailableModules: true,
        minimizer: [
            new TerserPlugin({
                terserOptions: {
                    format: {
                        comments: false,
                    },
                },
                extractComments: false,
            }),
        ],
    },
}
```

**What is the expected behavior?**
content should be equal from build to build

**Other relevant information:**
webpack version:  5.10.3
Node.js version: 12.19.0
Operating System: 
Additional tools:
- webpack-cli: 4.2.0
- terser-webpack-plugin: 5.0.3, the same as in webpack

**Comment by rifler** [comment]
I realize that if I change config to:
```diff
{
    mode: 'production',
    optimization: {
        runtimeChunk: 'single',
        removeAvailableModules: true,
        minimizer: [
            new TerserPlugin({
-                terserOptions: {
-                    format: {
-                        comments: false,
-                    },
-                },
                extractComments: false,
            }),
        ],
    },
}
```

All works fine...

**Comment by sokra** [comment]
I guess the real content hashing hides the real problem. Could you set `optimization.realContentHash: false` and compare it again.

**Comment by sokra** [comment]
And maybe also try with minimizing disable `optimization.minimize: false`

**Comment by alexander-akait** [comment]
Also check you don't have other minimizers or maybe you have minimizer inside `plugins`

**Comment by rifler** [comment]
> I guess the real content hashing hides the real problem. Could you set `optimization.realContentHash: false` and compare it again.

I will try, but I compare real files:

>But they don't differ significantly:
https://www.diffchecker.com/Szw487ot
> just two variables swap their names - l to f and f to l

**Comment by alexander-akait** [comment]
@rifler if you can create reproducible test repo, I can look at the problem

**Comment by rifler** [comment]
> if my assumption turns out to be true, there will be more differences then. I think even the filenames of the css files differ

You are right, with disabled `realContentHash` and `minimize` there are more differences - all in `css` files. But content of that files are the same.

We use array of configs (for each lang) and I realize, that we are instantiating Terser and MiniCssExtractPlugin once for all configs instead of instantiating for each config separately.

But after fixing it nothing changes - css hashes still were different.

After that I update `mini-css-extract-plugin` from `1.3.6` to `1.3.9` and it looks like everything has been fixed. I think it was fixed in https://github.com/webpack-contrib/mini-css-extract-plugin/issues/701

**Comment by saurishkar** [comment]
Still facing issue, but instead of css files I am seeing diff in chunk names.
Have disabled `minimize` and `realContentHash`.

If I enable both of them, I only see the `runtimeChunk` hash changing.
Can you guide me as to what might be causing this issue ?

Webpack version: `5.74.0`
Additional information: Using NextJs framework inside a monorepo.




<img width="1489" alt="Screenshot 2022-12-20 at 1 08 39 PM" src="https://user-images.githubusercontent.com/19742306/208610221-3da7217a-8506-4840-98a2-77b27a399e8f.png">

**Comment by alexander-akait** [comment]
@saurishkar Only js files wash changed? can you look at content, it was changed (and what is changed)?

**Comment by saurishkar** [comment]
@alexander-akait Yes, only js chunks' hashes got changed even though there were no changes in code.
Also, this is random. If I trigger the build again for the same commit on the same system, the hashes get changed for different chunks so the chunks that are being modified is not consistent as well.

**Comment by alexander-akait** [comment]
@saurishkar sounds weird, do you have the latest version of `NextJs`? Maybe a bug on their side...

**Comment by saurishkar** [comment]
@alexander-akait I am using Next 12.3.4.
On further debugging, I found out that the chunks which were getting modified was due to the sourcemapUrl being updated at the last of that file 🤦🏽‍♂️ 

So, looks like the sourcemapping is modifying the file causing the webpack chunk to eventually change.

I disabled the sourcemaps to check if it changes anything but surprisingly the hash id's still gets modified on successive builds.
When I dived in deeper to check the actual content, this time to another surprise, I found them to be identical !
😄 

It seems weird why the hash ids will be changing even though the content now is identical 🤔 
Any suggestions ?

**Comment by saurishkar** [comment]
I think I will have to check with NextJs team as well as when I downgrade Next to 12.1.0, this problem seems to go away 🥲

**Comment by alexander-akait** [comment]
@saurishkar 

> It seems weird why the hash ids will be changing even though the content now is identical thinking
Any suggestions ?
> I think I will have to check with NextJs team as well as when I downgrade Next to 12.1.0, this problem seems to go away smiling_face_with_tear

Yeah, sounds like a bug in NextJs, without code hard to say what is wrong, I think better to open an issue in NextJs repo

> On further debugging, I found out that the chunks which were getting modified was due to the sourcemapUrl being updated at the last of that file 🤦🏽‍♂️

Just idea, do you have extra `\n` (`\r\n`) after `sourcemapUrl` (try to use hex editor to see all character)

**Comment by saurishkar** [comment]
> Just idea, do you have extra \n (\r\n) after sourcemapUrl (try to use hex editor to see all character)

Sure, will try to check this out.

**Comment by romanlex** [comment]
@saurishkar 
did you find the source of the problem?

**Comment by saurishkar** [comment]
@romanlex Unfortunately I wasn't able to exactly pinpoint but it was something to do with the loaders being used in webpack.
I overcame this by keeping a single consistent build across my multi server deploys and uploading the build assets on a external storage like s3 so that even if the hashId changes, the information is not lost for the older files.
