### ISSUE TITLE
Webpack Hash is not FIPS-Compliant

### ISSUE THREAD

**Issue by BurntCoffee543** [webpack/webpack#13572]
# Bug report

**What is the current behavior?**
Building on a FIPS-enabled system, the digest "md4" is not supported (and furthermore is not FIPS-compliant). Upon building, the following error is thrown...

<pre><code>UnhandledPromiseRejectionWarning: Error: Digest method not supported
    at new Hash (internal/crypto/hash.js:46:19)
    at Object.createHash (crypto.js:115:10)
    at module.exports (omitted_root_path/node_modules/webpack/lib/util/createHash.js:135:53)
    at ConcatenatedModule._createIdentifier (omitted_root_path/node_modules/webpack/lib/optimize/ConcatenatedModule.js:563:16)
    at new ConcatenatedModule (omitted_root_path/node_modules/webpack/lib/optimize/ConcatenatedModule.js:445:27)</code></pre>

The issue is that some of the modules have "md4" hardcoded in (unconfigurable) such as the ConcatenatedModule.

**If the current behavior is a bug, please provide the steps to reproduce.**
I cannot easily link a StackBlitz or GitHub repo as [fips has to be enabled on the Node distribution](https://nodejs.org/dist/latest-v14.x/docs/api/cli.html#cli_enable_fips). The following is the custom-webpack config...

<pre><code>const webpack = require('webpack');
 
module.exports = {
  output: {
    hashFunction: 'sha256'
  },
  plugins: [
    new webpack.HashedModuleIdsPlugin({
      hashFunction: 'sha256'
    })
  ]
};</pre></code>

**What is the expected behavior?**
For any use of a hash, there should be option to configure the underlying algorithm via the custom-webpack config. This [StackOverflow post](https://stackoverflow.com/questions/67427243/cant-build-angular-9-project-on-rhel-8-with-fips-enabled) suggests a workaround of disabling the ConcatenatedModule, but any hardcoded hashing algorithm should be configurable so that they can run on FIPS-enabled systems.

**Other relevant information:**
webpack version: 4.44.2
Node.js version: 14.16.0
Operating System: RHEL

**Comment by alexander-akait** [comment]
Please update webpack to v5

**Comment by BurntCoffee543** [comment]
@alexander-akait I definitely plan to in the future, but I am currently limited by Angular 11 and @angular-builders/custom-webpack 11 which use Webpack 4 as its underlying dependency. Any advice for handling this?

**Comment by alexander-akait** [comment]
Only monkey patching webpack

**Comment by BurntCoffee543** [comment]
@alexander-akait We recently upgraded to Webpack 5.40.0 and are running into issues with the md4 hash in [ChunkGraph.js](https://github.com/webpack/webpack/blob/v5.40.0/lib/ChunkGraph.js) and [FileSystemInfo.js](https://github.com/webpack/webpack/blob/v5.40.0/lib/FileSystemInfo.js). Any way to handle this? Thanks!

**Comment by alexander-akait** [comment]
I want to say you need md4 support to works with webpack

**Comment by martinpitt** [comment]
This is an issue with the very latest webpack 5.53.0 as well. Fedora Rawhide/CentOS 9 stream/upcoming RHEL 9 switched to OpenSSL 3.0, which does not offer `md4`. So instead of thousands of projects figuring out the [output.hashFunction hack](https://webpack.js.org/configuration/output/#outputhashfunction) by themselves, maybe it's time to just switch the default to sha256?

**Comment by martinpitt** [comment]
Also, merely setting `output.hashFunction` does not suffice at all. `grep -r createHash.*md4 node_modules/webpack` shows no less than 21 (!) places which hardcode an md4 hash. For example, in https://github.com/cockpit-project/starter-kit I get a crash in ChunkGraph:

```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/src/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.digest (/src/node_modules/webpack/lib/util/createHash.js:80:21)
    at /src/node_modules/webpack/lib/ChunkGraph.js:1494:51
    at RuntimeSpecMap.provide (/src/node_modules/webpack/lib/util/runtime.js:495:33)
    at ChunkGraph._getModuleGraphHashBigInt (/src/node_modules/webpack/lib/ChunkGraph.js:1489:37)
    at /src/node_modules/webpack/lib/ChunkGraph.js:1517:27
    at RuntimeSpecMap.provide (/src/node_modules/webpack/lib/util/runtime.js:495:33)
    at ChunkGraph._getModuleGraphHashWithConnections (/src/node_modules/webpack/lib/ChunkGraph.js:1516:41) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by alexander-akait** [comment]
@martinpitt I see, PR welcome, should not hard

**Comment by alexander-akait** [comment]
Ideally we should respect `hashFunction`

**Comment by martinpitt** [comment]
In case someone else is blocked by this: I just added a hack to [monkey-patch crypto.createHash()](https://github.com/cockpit-project/starter-kit/commit/3220617fec508aabbbc226a87a165c21fb72e913) in webpack.config.js, which has the advantage that no static patches to `node_modules/` are necessary:
```js
const crypto = require("crypto");
const crypto_orig_createHash = crypto.createHash;
crypto.createHash = algorithm => crypto_orig_createHash(algorithm == "md4" ? "sha256" : algorithm);
```
This is an ugly, but working crutch until webpack gets updated.

**Comment by martinpitt** [comment]
I'm happy to send a PR which just replaces all `md4` with `sha256`, but that might not be what you had in mind?

> Ideally we should respect `hashFunction`

You mean some config option in webpack.config.js? Is that actually visible anywhere, or just an internal implementation detail? In the latter case, it seems better to not expose it as a config?

**Comment by alexander-akait** [comment]
We already have `output.hashFunction`

**Comment by sokra** [comment]
These instances where md4 is used are not required to be cryptographically correctly hashed. It's more about being fast, and md4 was the fastest one at that time.

But we can replace that with a faster wasm-based hashing implementation (xxhash3) now.

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/14306

**Comment by stanhu** [comment]
I'd like to backport https://github.com/webpack/webpack/pull/14306 to Webpack 4 since it appears that we cannot update to Webpack v5 at the moment until we also update to Vue 3.

https://github.com/webpack/webpack/pull/14306#issuecomment-924892934 mentions this as an open item. 

@alexander-akait @sokra Would you be open to a pull request that backports this to Webpack 4?

**Comment by alexander-akait** [comment]
@stanhu Sorry, backporting is not easy and requires a lot of changes, I'm afraid it's just not possible, because there are many loaders/plugins also uses md4

**Comment by darmbrust** [comment]
Has this been tested by anyone on a FIPs system?
It still doesn't seem to work.  

Using webpack 5.64.4, setting  output:
```
output: {
    hashFunction: 'xxhash64',
```

It still results in:
```
ERROR in ./src/assets/img/IMG.svg
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
    at new Hash (internal/crypto/hash.js:46:19)
    at Object.createHash (crypto.js:114:10)
    at getHashDigest (/workspace/node_modules/file-loader/node_modules/loader-utils/lib/getHashDigest.js:52:30)
    at /workspace/node_modules/file-loader/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at Object.interpolateName (/workspace/node_modules/file-loader/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/workspace/node_modules/file-loader/dist/index.js:28:36)
```


Additionally, I've tried messing with the options on the file-loader:

```use: [{
              loader: "file-loader",
              options: {
                name: "static/media/[name].[hash:8].[ext]",
                hash: "sha256",
                contenthash: "sha256",
              },
            }],
```
Though, I am rather confused by the lack of clear documentation to differentiate hash, contenthash, and hashType as documented on the file-loader.  Nor do I have any idea if / how these interact with the hashFunction.... And then url-loader doesn't document an option to specify the hash type.... https://v4.webpack.js.org/loaders/file-loader/#hash

Maybe I'm just missing something obvious in the doc....

**Comment by Artoria2e5** [comment]
The current approach of shipping an asmjs md4 and wasm xxhash3 should work around the system's FIPS policy -- so long as it does not touch `crypto`, nothing should get flagged.

[`xxhash` does not work with `file-loader` because f-l does not have support for it, so it falls back to `crypto` (which does not have an implementation anyways even for non-FIPS).]

> These instances where md4 is used are not required to be cryptographically correctly hashed. It's more about being fast, and md4 was the fastest one at that time.

True, because hashing is currently just done against (1) module identifier (2) (for `[contenthash]`, `[chunkhash]`) asset file content, both of which should be controlled entirely by the developer. (1) should be hard to collide mostly; (2) can be possibly triggered by someone shipping a real MD4 collision in their project.
