### ISSUE TITLE
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null` (5.47.0)

### ISSUE THREAD

**Issue by RyanMarcotte** [webpack/webpack#13879]
# Bug report

The latest version of webpack (`5.47.0`) causes our build pipeline to fail due to some missed `null` check.  Our project has both the backend and frontend built and deployed as a single unit and no frontend changes were made between a backend-exclusive code change successfully merged and deployed yesterday evening and our builds (now failing) this morning.

![image](https://user-images.githubusercontent.com/1458084/127197702-ee582fbb-2311-4764-b9db-e024731dda74.png)

**Comment by Jeniczech** [comment]
Hello there, we have been experiencing the exactly same issue. What helped was removing `devtool: 'source-map'` from our webpack config. I have absolutely no idea why this resolved the issue, but it worked!

**Comment by sokra** [comment]
Should be fixed in 5.47.1.

Could you verify that?

**Comment by Superoryco** [comment]
> Should be fixed in 5.47.1.
> 
> Could you verify that?

npm not available yet?

**Comment by sokra** [comment]
I released it an hour ago, but npm seem to be really slow propagating that... It also took an hour to get the 3.1.1 version of webpack-source on npm.

You can also update webpack-sources in your lockfile...

**Comment by Superoryco** [comment]
I have no chance to reproduce the excpetion from 'streamChunksOfCombinedSourceMap.js' in my project. @modestfake @ryanbraganza could have a try.
but
I've install 5.47.1 throw `yarn add webpack/webpack#5.47.1`,  still throw 'length' of null in file [ReplaceSource.js](https://github.com/webpack/webpack-sources/blob/5024ff8d42c97b24a32f60b4d0cffa2b5c3a49dd/lib/ReplaceSource.js#L169), may be it is another bug need to be fixed?

**Comment by sokra** [comment]
> may be it is another bug needs to be fixed?

Possible. If you have a repro, I'm happy to fix that.

**Comment by Superoryco** [comment]
> Possible. If you have a repro, I'm happy to fix that.

Interesting...I copied all files in my project into a new folder to reproduce, after a fresh npm install, it works with 5.47.1...so I guess problem solved...

**Comment by modestfake** [comment]
I'm using Electron Forge with Webpack + Typescript template. I've tried to reproduce it on a fresh build but I can't reproduce, it might be some specific library affecting it. Anyway, I still can reproduce it on my project but it's resolved when I apply [this fix](https://github.com/webpack/webpack-sources/pull/121/files#diff-f329bbe4a7550e22eab81127f2b24fac3032e9b14df5268fdc2021acb7086ea5). If you want, I can push my project to GitHub private repo and give you access so you can try to reproduce it.

One note, I noticed that I can reproduce the error from `streamChunksOfCombinedSourceMap.js` when I run `npm run make` and there's no problems when I run `npm start`. If you take a look at the Webpack plugin they use https://github.com/electron-userland/electron-forge/tree/master/packages/plugin/webpack, the only difference I can see it that when I run `npm start` it uses `devtool: 'evel-source-map` but with `npm run make` it's `source-map` and this is where it's reproducible. Here's source https://github.com/electron-userland/electron-forge/blob/master/packages/plugin/webpack/src/WebpackConfig.ts#L52

Let me know if that rings any bell if not, I can try to give you access to a private repo or merge https://github.com/webpack/webpack-sources/pull/121 to fix it (but yeah, it would be great to know why it's failing rather than blindly fix it).

**Comment by modestfake** [comment]
Alright, I was able to reproduce it.

## Steps to reproduce:
```bash
# 1. https://www.electronforge.io/templates/typescript-+-webpack-template
npx create-electron-app reproduce-webpack-source-error --template=typescript-webpack

cd reproduce-webpack-source-error

npm ls webpack-sources
# repro-webpack-sources-bug@1.0.0 /Users/dev/repro-webpack-sources-bug
└─┬ @electron-forge/plugin-webpack@6.0.0-beta.59
  └─┬ webpack@5.47.1
    └── webpack-sources@3.1.1

# This one works fine after the latest fix
npm start

# This one work for now
npm run make

# But let's install electron-store and init it (https://github.com/sindresorhus/electron-store)
npm i electron-store
```

Open `/reproduce-webpack-source-error/src/index.ts`
Add
```javascript
import Store from 'electron-store'

const store = new Store()
```

```bash
# Then run this one more time
npm run make
```

This time it should fail. I guess it might be related to `native_modules` but I don't know how it works. Maybe [this part of the Electron Forge Webpack config](https://github.com/electron-userland/electron-forge/blob/master/packages/template/typescript-webpack/tmpl/webpack.rules.js#L7-L16).

**Comment by Superoryco** [comment]
> Electron Forge with Webpack + Typescript

Actually, I'm also using Electron Forge with Webpack + Typescript, and electron-store, never tried 'npm run make' before.

>One note, I noticed that I can reproduce the error from streamChunksOfCombinedSourceMap.js when I run npm run make and there's no problems when I run npm start

Confirm: For 5.47.1, it did fix the 'length of null' error from 'ReplaceSource.js', with 'npm run make', still throw same error from 'streamChunksOfCombinedSourceMap.js', 

Also, to fix this bug, I think we can just apply [this](https://github.com/webpack/webpack-sources/pull/121/files#diff-f329bbe4a7550e22eab81127f2b24fac3032e9b14df5268fdc2021acb7086ea5), after I digg into the code:

`originalSourceLines = originalSource? originalSource.match(SPLIT_LINES_REGEX): null;`

`originalSourceLines` is a nullable variable but we missed the null check, that's it, I think.
