### ISSUE TITLE
update of `webpack-sources` breaks our bundling in production mode

### ISSUE THREAD

**Issue by paul-marechal** [webpack/webpack#13887]
# Bug report

The issue happens in the [Theia repository](https://github.com/eclipse-theia/theia) where Webpack emits a bogus bundle in production mode.

I tracked this issue down to the update to `webpack-sources`: https://github.com/webpack/webpack/commit/c3a0145b49e62fbda7fe1372b87b0cef517a6c7f

Any version `webpack-sources@3` fails our build, previous versions seem to work fine.

**What is the current behavior?**

Bogus bundle code being emitted, such as:

```js
ffunction then(...
```

Note the duplicated `f` from `function`.

The exact error is:

```
ERROR in bundle.js from Terser
Unexpected token: name (then) [webpack://../node_modules/es6-promise/dist/lib/es6-promise/-internal.js:129,4][bundle.js:46850,10]
    at js_error (theia\node_modules\terser\dist\bundle.min.js:548:11)
    at croak (theia\node_modules\terser\dist\bundle.min.js:1272:9)
    at token_error (theia\node_modules\terser\dist\bundle.min.js:1280:9)
    at unexpected (theia\node_modules\terser\dist\bundle.min.js:1286:9)
    at semicolon (theia\node_modules\terser\dist\bundle.min.js:1324:56)
    at simple_statement (theia\node_modules\terser\dist\bundle.min.js:1581:73)
    at statement (theia\node_modules\terser\dist\bundle.min.js:1394:19)
    at _embed_tokens_wrapper (theia\node_modules\terser\dist\bundle.min.js:1337:26)
    at block_ (theia\node_modules\terser\dist\bundle.min.js:2170:20)
    at _function_body (theia\node_modules\terser\dist\bundle.min.js:2082:21)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Building a Theia application has a few [prerequisites](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites).

Unless you know how to skip node-gyp building, you'll need to have the proper shared libraries installed on Linux.

```sh
git clone https://github.com/eclipse-theia/theia.git
cd theia
git checkout 3716c0716f4f7fe30ef5b36faff4f85e833b20be
yarn upgrade
yarn # you can CTRL+C once you see linting output...
cd examples/browser
# <checkpoint>
yarn theia build # this runs webpack in production mode among other things
```

The above steps should lead to the error.

You can start again from `<checkpoint>` and edit `webpack.config.js` to add:

```js
config.optimization = {
    minimize: false
};
```

This will allow you to take a look at the generated bundles. The bogus generation should be in `lib/bundle.js` line 46850.

**What is the expected behavior?**

Emitted code to not be bogus, notably the duplicated `f` character in the previous examples.

**Other relevant information:**
webpack version: 5.47.0
Node.js version: 12.22.3
Operating System: Windows 10
Additional tools: n/a

**Comment by sokra** [comment]
Yep, we are currently in progress of sorting out some bugs in the new implementation.

I think this one should be fixed in webpack-sources@3.0.3, but not sure and there is at least one other bug that we know about, and going to fix hopefully today.

**Comment by paul-marechal** [comment]
> I think this one should be fixed in webpack-sources@3.0.3

We experienced the issue with 3.0.0 up to 3.0.3 included.

**Comment by sokra** [comment]
Could you try `webpack@5.47.1`?

**Comment by paul-marechal** [comment]
@sokra should I wait for it to be published on npm?

I just tried it using `yarn link` locally:

- I cloned this repository, ran `yarn` and then `yarn link`.
- I moved to a fresh clone of our repository, ran `yarn link webpack` and made sure there's no duplicated package.

After running the bundling it still failed. Here's some diagnostics (Windows's cmd.exe):

```batch
rem go next to webpack's linked folder
theia>cd node_modules\webpack

rem check what version of `webpack-sources` the linked `webpack` sees:
theia\node_modules\webpack>node -p "require('webpack-sources/package.json').version" 
3.1.1

rem go back at the root of our repo
theia\node_modules\webpack>cd ..\..   

rem webpack seems to be the updated version:
theia>npx webpack -v
webpack 5.47.1
webpack-cli 4.7.0
```

Looks like I was using the updated packages, still a bundling failure, same place.

**Comment by paul-marechal** [comment]
Just tried again using the published updates just in case, and still the same issue.

**Comment by sokra** [comment]
I try to run your repo...

**Comment by sokra** [comment]
I can reproduce it, but that's not going to be fun to find in that 17MB source + 19MB source map processing...

**Comment by sokra** [comment]
> I can reproduce it, but that's not going to be fun to find in that 17MB source + 19MB source map processing...

Ok it will be easier than expected as it's somehow caused by the SourceMap of es6-promise...

**Comment by sokra** [comment]
Ok it's caused by a weird SourceMap of es6-promise. It contains:

### 0 sized mappings

```
20:0 -> [lib/es6-promise/utils.js] 6:0, :0 -> [lib/es6-promise/utils.js] 6:7, :9 -> [lib/es6-promise/utils.js] 6:16, :19 -> [lib/es6-promise/utils.js] 6:26, :20 -> [lib/es6-promise/utils.js] 6:27, :21 -> [lib/es6-promise/utils.js] 6:28, :23 -> [lib/es6-promise/utils.js] 6:30
function isFunction(x) {
^________^_________^^^_^
```

column 0 is mapped to `[lib/es6-promise/utils.js] 6:0` and `[lib/es6-promise/utils.js] 6:7`, which doesn't really makes sense.

### non-monotonic ordered mappings

```
161:1 -> [lib/es6-promise/asap.js] 123:1, :0 -> [lib/es6-promise/then.js] 5:15, :9 -> [lib/es6-promise/then.js] 5:24, :13 -> [lib/es6-promise/then.js] 5:28, :14 -> [lib/es6-promise/then.js] 5:29, :27 -> [lib/es6-promise/then.js] 5:42, :29 -> [lib/es6-promise/then.js] 5:44, :40 -> [lib/es6-promise/then.js] 5:55, :42 -> [lib/es6-promise/then.js] 5:57
function then(onFulfillment, onRejection) {
.^_______^___^^____________^_^__________^_^
```

column 1 is mapped before column 0.

---

I'll now ignore all mappings that don't have an increasing column index. Basically dropping invalid mappings.

But that should probably fixed in the source map generation, since some of these mappings are really weird. e. g. mapping to `asap.js` instead of `then.js`. @stefanpenner

**Comment by sokra** [comment]
fix in `webpack-sources@3.1.2`

**Comment by paul-marechal** [comment]
I just tried your updates, and now I get:

```
(node:2928) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at innerSourceIndex (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunksOfCombinedSourceMap.js:173:50)
    at onMapping (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunksOfSourceMap.js:294:4)
    at readMappings (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\readMappings.js:61:6)
    at streamChunksOfSourceMapFinal (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunksOfSourceMap.js:309:2)
    at module.exports (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunksOfSourceMap.js:382:6)
    at streamChunksOfCombinedSourceMap (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunksOfCombinedSourceMap.js:54:9)
    at SourceMapSource.streamChunks (theia\node_modules\webpack\node_modules\webpack-sources\lib\SourceMapSource.js:192:11)
    at module.exports (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
    at ConcatSource.streamChunks (theia\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
    at exports.getSourceAndMap (theia\node_modules\webpack\node_modules\webpack-sources\lib\helpers\getFromStreamChunks.js:17:33)
    at ConcatSource.sourceAndMap (theia\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:94:10)
    at getTaskForFile (theia\node_modules\webpack\lib\SourceMapDevToolPlugin.js:84:30)
    at theia\node_modules\webpack\lib\SourceMapDevToolPlugin.js:272:22
    at theia\node_modules\webpack\lib\Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (theia\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Cache.get (theia\node_modules\webpack\lib\Cache.js:75:18)
    at ItemCacheFacade.get (theia\node_modules\webpack\lib\CacheFacade.js:117:15)
    at theia\node_modules\webpack\lib\SourceMapDevToolPlugin.js:223:18
    at arrayEach (theia\node_modules\neo-async\async.js:2405:9)
    at Object.each (theia\node_modules\neo-async\async.js:2846:9)
    at theia\node_modules\webpack\lib\SourceMapDevToolPlugin.js:207:15
    at fn (theia\node_modules\webpack\lib\Compilation.js:481:9)
```

**Comment by paul-marechal** [comment]
Note that I get that same TypeError even when removing all references to `es6-promise`.

**Comment by paul-marechal** [comment]
I was about to look at fixing the TypeError and found https://github.com/webpack/webpack-sources/pull/121

This PR along with your most recent changes fix the issue we are having, thanks!

**Comment by alexander-akait** [comment]
Fixed, feel free to feedback
