### ISSUE TITLE
resolve.alias not works

### ISSUE THREAD

**Issue by raminious** [webpack/webpack#4160]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Resolve.alias not works as mentioned in https://webpack.js.org/configuration/resolve/#resolve-alias

```
/* ./webpack/base.js */
  ...
  resolve: {
    extensions: [ '.js', '.json', '.css' ],
    modules: [
      config.compile.entry,
      'node_modules'
    ],
    alias: {
      Actions: config.compile.entry + '/actions/'
    }
  }
  ...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
1- git clone https://github.com/raminious/react-universal-boilerplate
2- cd react-universal-boilerplate
3- git checkout webpack-alias
4- yarn (or npm install)
5- npm run dev
```

**What is the expected behavior?**
`import { types } from 'Actions/app'` should work but getting this error:
` Error: Cannot find module 'Actions/app' `

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node version: v6.6.0
Webpack version: 2.2.1
OS: OSX El Capitan

**Comment by trusktr** [comment]
What is the value of `config.compile.entry`? Are you sure the final path is correct?

**Comment by raminious** [comment]
@trusktr You can find it in `config/index.js` file
```
const config = {
  compile: {
    entry: path.resolve(__dirname, '../src')
  }
}
```

Yes I doubt and checked that many times, that was okay

**Comment by dontwork** [comment]
I am having the same issue. resolve.alias seems to be doing absolutely nothing

**Comment by kuakman** [comment]
Same here! I was kicking tires with a simple sample using 2.2.1 and I'm facing the same issue.

**Comment by adriaanbalt** [comment]
same

**Comment by sokra** [comment]
Could you update `enhanced-resolve` and check again?

**Comment by raminious** [comment]
@sokra I updated to `enhanced-resolve@3.1.0` and still getting same error

**Comment by andreevWork** [comment]
+1 same error

**Comment by raminious** [comment]
@sokra Any good news ?

**Comment by davidgilbertson** [comment]
This happens for me:
1. set up the alias: `OurComponents: path.resolve(__dirname, '../app/components/index.js'),`
2. use it in one file like `import {App} from 'OurComponents';`
3. start webpack (dev server)

Works fine 🥇 

4. Add it to another file, like `import {Hamburger} from 'OurComponents';`
5. Refresh the page

Works fine

6. Restart webpack (not making _any change to the code_)

I get `Error: Cannot find module 'OurComponents'`

So for me at least it seems to be something when it's used in more than one file and when webpack is first starting causing this error, that isn't happening when webpack is re-compiling or when it's only used in one file.

The full thing:
```
Error: Cannot find module 'OurComponents'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/web/davidg-site/app/components/App/App.jsx:12:1)
    at Module._compile (module.js:573:32)
    at loader (C:\web\davidg-site\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (C:\web\davidg-site\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

**Comment by guoerwei** [comment]
I set `resolve.alias = path.resolve(__dirname, './src/styles/')`
and when I use `import "styles/common.css"` it failed,
getiing error : `Cannot find module 'styles/common.css'`

but when i use `require('styles/common.css')` it just worked
what happened?

**Comment by epitaphmike** [comment]
I am doing this successfully in a new project, and it seems to be working well. What I am doing is:

**base-ui/client/package.json**
``` javascript
"devDependencies": {
    ...
    "webpack": "^2.2.0"
}
```

**webpack.dev.config.js**
``` javascript
resolve: {
            modules: [path.resolve('./node_modules')],
            alias: {
                Common: path.resolve(__dirname, '../../../../base-ui/client')
            },
            extensions: ['.js', '.jsx', '.json', '.scss']
        },
```
We have different applications that use the components inside "base-ui" and these applications live in the same parent directory as base-ui. 

**base-ui/client/components/index.js**
``` javascript
export { default as Button } from './button/Button';
export { default as SingleInput } from './singleInput/SingleInput';
```

**base-ui/client/components/button/Button.jsx**
``` javascript
...
export default Button
```

In these applications we can do things like:

**account-ui/client/page/ForgotPassword.jsx**
``` javascript
import { Button, SingleInput } from 'Common/components';
```

This method seems to be working across the board. It has it's challenges when it comes to Jest testing and using things like wallabyjs which I am still figuring out, but as for webpack and ```resolve.alias``` it is working great.

I hope this helps.

**Comment by aryzing** [comment]
In my case, I don't get any errors, but the *exact same import* in two different files produces different values:

```js
// file 1:
import { StatusBar } from 'Components' // works great!

// file 2:
import { StatusBar } from 'Components' // undefined :(
```

Also, just as a friendly reminder, if you're using Babel, make sure you deactivate modules,

```js
{
  "presets": [["env", {"modules": false}], "react"],
}
```

**Comment by davidgilbertson** [comment]
@epitaphmike which OS? I'm using Windows, was doing something very similar and it wasn't working. `alias.modules` isn't working for me either.

**Comment by epitaphmike** [comment]
I am using OS X El Capitan.

**Comment by davidgilbertson** [comment]
I wonder if this is a Windows issue then. I've just tried `resolve.modules` instead of `resolve.alias` and it doesn't work either.

Hopefully I just doing something dumb. Should the below work in theory?

I have a file `my-site/buildTools/dev.js` with my dev config that looks in part like this:

```js
    resolve: {
        modules: [
            path.resolve(__dirname, '../app'),
            'node_modules',
        ],
    },
```

(I've tried fifty different combos of relative paths and absolute paths)

Then I have `my-site/app/components/index.js`:
```js
export { default as Home } from './pages/Home/Home';
```

(I've also tried doing this as `my-site/app/components.js`)

Then I import my component like so
```js
import { Home } from 'components'; // "cannot find modules 'components'"
```
But the below two methods work, so I know at least the paths are right:

```js
import Home from '../pages/Home/Home'; // works
import { Home } from '../../components/index.js'; // works
```

Could it be another part of my setup? I wonder if using `babel-register` is causing the problem.

**Comment by epitaphmike** [comment]
I am not using babel-register anywhere.

My main babel imports include

**base-ui/client/package.json**
```
"devDependencies": {
    "babel-jest": "^18.0.0",
    "babel-plugin-transform-class-properties": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.22.0",
    "babel-polyfill": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.22.0",
    "enzyme": "^2.7.1",
    "enzyme-to-json": "^1.4.5",
    "fetch-mock": "^5.9.3",
    "jest": "^18.1.0",
    "jest-fetch-mock": "1.0.5",
    "nock": "^9.0.2",
    "react": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-test-renderer": "^15.4.2"
  },
```

also I made a few adjustments in our directory structure that you may want to try. 

**base-ui/client/components/button/**
```
button----
    Button.jsx
    index.js
    propTypes.js
```

**base-ui/client/components/button/Button.jsx**
```
import React from 'react';
import RaisedButton from 'material-ui/RaisedButton';
import { buttonProps } from './propTypes';

const Button = ({ label, style = {}, href, onClick }) => (
    <RaisedButton
        label={ label }
        style={ style }
        href={ href }
        onMouseUp={ onClick }/>
);

Button.PropTypes = buttonProps;

export default Button;
```
**base-ui/client/components/button/index.js**
```
import Button from './Button';
export default Button;
```

**base-ui/client/components/index.js**
```
export { default as Button } from './button';
```

**account-ui/client/page/ForgotPassword.jsx**

This is unchanged.
```
import { Button, SingleInput } from 'Common/views/components';
```

**Comment by filmic** [comment]
I had a similar issue with aliases not working. I fixed it by removing `node_modules` folder and installing packages again (running `yarn`).

**Comment by gozes** [comment]
@filmic  I had the same issue even do I am using yarn and did that still got the issue

**Comment by Ewocker** [comment]
Same issue here. 
Node version: v6.10.1
Webpack version: 2.2.1
OS: OSX El Capitan
```
resolve: {
  extensions: ['.js', '.vue', '.json'],
  alias: {
    '@': resolve('src')
  }
},
```

```
import App from '@/App.vue'
```

ERROR in ./src/js/dashboard.js
Module not found: Error: Can't resolve '@/App.vue'

**Comment by briandipalma** [comment]
The `AliasPlugin` in enhanced-resolve looks to be operating correctly, it changes the `request` obj as you expect in this code https://github.com/webpack/enhanced-resolve/blob/0d0c5f09a03a03399d7344e56a2810c3aa212c0e/lib/AliasPlugin.js#L45

I think the issue is that the alias value isn't an absolute path, so it's the resolving following the alias changes that fails. I'll debug a bit more.

**Comment by briandipalma** [comment]
The `UnsafeCachePlugin` seems to be the only `enhanced-resolve` plugin applied to the newly constructed request object, both `before` and `after` resolve appear to have no plugins registered so it's applied at the `resolve` stage.

https://github.com/webpack/enhanced-resolve/blob/0d0c5f09a03a03399d7344e56a2810c3aa212c0e/lib/UnsafeCachePlugin.js#L29

**Comment by briandipalma** [comment]
It looks to me like the `ModulesInHierachicDirectoriesPlugin` doesn't handle absolute `modules` values, joining an absolute directory to another absolute one will fail https://github.com/webpack/enhanced-resolve/blob/0d0c5f09a03a03399d7344e56a2810c3aa212c0e/lib/ModulesInHierachicDirectoriesPlugin.js#L24 ?

**Comment by briandipalma** [comment]
It doesn't look like `modules` would ever be passed into `enhanced-resolve`, if we use this resolver https://github.com/webpack/enhanced-resolve/blob/0d0c5f09a03a03399d7344e56a2810c3aa212c0e/lib/node.js#L18 the options are hardcoded in during creation...

**Comment by briandipalma** [comment]
That means our resolver has these options hardcoded into it and our webpack config options aren't applied https://github.com/webpack/enhanced-resolve/blob/0d0c5f09a03a03399d7344e56a2810c3aa212c0e/lib/ResolverFactory.js#L38

**Comment by briandipalma** [comment]
OK so I was looking at the wrong resolver creation, it's this one that is used by webpack https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L283 and that's OK it does get the webpack config options.

**Comment by briandipalma** [comment]
request.module is false even though the alias is pointing toward a module https://github.com/webpack/enhanced-resolve/blob/0d0c5f09a03a03399d7344e56a2810c3aa212c0e/lib/ModuleKindPlugin.js#L16

Should we use `onlyModule: true` for aliases from now on?

**Comment by briandipalma** [comment]
It appends the file extension and the `FileExistsPlugin` checks if the file exists, then after a while you get an error that the file without the `.js` extension doesn't exist (which it doesn't) you then expect the file with `.js` to be found (it does exist at the `path`) but we then get a ModuleNotFound error. Is it not allowing all the plugins to complete execution?

**Comment by briandipalma** [comment]
It looks like every new entry to resolve.modules increases build time linearly
 
I think webpack keeps looking for modules even after a file has been found, given it's async/callback approach it's very hard to cancel ongoing work, is that correct?

**Comment by jspears** [comment]
I am not positive this is the same issue, however I created a project that shows that alias order matters, and it probably should not (since a hash does not guarantee order). I can open a seperate bug report if deemed not the same as this one. With  webpack 2.4.1.

See Sample Repo:
https://github.com/jspears/webpack-alias-bug

But might be useful to have another sample of the issue.

**Comment by rossjp** [comment]
Same issue. Is this still being investigated?

**Comment by mcrawshaw** [comment]
I can't get it working at all.

I've been searching the test cases, I can't find a test for ```alias```.  Does anyone know of one?

@jspeas, maybe a separate issue for ordering.  @raminious original issue only has one alias.

**Comment by dlong500** [comment]
This is crazy.  I can't seem to get anything at all to work with `resolve.alias` (on Windows 7 x64 with webpack 2.4.1 and node 6.10.1).  I'm going to try to find a few boilerplate repos using `alias` to see if I can get any of them to compile.  I just wanted to start cleaning up a project that has a bunch of relative paths and stumbled upon this issue after banging my head against a wall for an hour.  Is this an isolated issue or are there people out there who aren't having any problems?

**Comment by jancassio** [comment]
@dlong500 try to use [this boilerplate](https://reactstarter.com), just put `resolve: {}` for example and you I'll be able to reproduce this issue.

**Comment by dlong500** [comment]
I've given up on this for now and just started using `babel-plugin-module-resolver` because I'm already using babel anyway.  That allows me to create the same type of aliases through a babel transform.

**Comment by MartanLV** [comment]
same issue here

**Comment by slawiko** [comment]
@filmic it works for me too! Thanks

**Comment by maxceem** [comment]
Same for me on Mac OS Sierra 10.12.3, node v.6.10.2 and webpack 2.2.1. It works using require though as pointed above.

**Comment by slawiko** [comment]
@sokra any updates? Is this a bug, or ... feature? :)

**Comment by bigfish** [comment]
I'm having the same issue. I'm aliasing multiple modules to filesystem dirs, and all of them work... except one. For this one, its looking relative to the 'src' directory of the app with the aliases.. ie, as if i said import './mymodule' instead of 'mymodule' .

**Comment by bigfish** [comment]
using `require('module')` works, and I also found that renaming the module in the import statement, and in the alias, causes it to work. perhaps some sort of caching problem?

**Comment by smoleniuch** [comment]
When im using alias like this one:

alias{
   H:path.resolve(__dirname,'resources/assets/handlebars')
}

and have loader for handle bars

{ test: /\.hbs$/, loader: "handlebars-loader" }

i have tested to require the same file but with different prefix,with .js extension that alias is working,but when i change extension to hbs im getting error too

**Comment by bigfish** [comment]
ah, I found my issue was that I was also using babel-resolver plugin 
https://www.npmjs.com/package/babel-plugin-resolver

seems like this plugin was eagerly trying to resolve the module name relative to the 'resolveDirs' rather than using the aliased value.

Switching to similar plugin https://github.com/tleunen/babel-plugin-module-resolver

fixed the issue. 

I will also mention this on the babel-plugin resolver github.

**Comment by kemhwd** [comment]
Having same issue.
I ended up using resolve.modules config instead for the time being.
 
`
resolve : { modules: [path.resolve(__dirname, "app"), "node_modules"] } 
`

So instead of referencing import file by relative path, you can reference it from the project directory.

**Comment by jancassio** [comment]
@kemhwd Why you added `"node_modules"` to `resolve.modules` list? Is one special reason for that?

**Comment by MartanLV** [comment]
my issue turned up, that I was wrongly using `path.resolve(__dirname, "app/some/path")`

correct is `path.resolve(__dirname, "app", "some", "path")` and that works... 

quite a lot comments on this issue xD

**Comment by kemhwd** [comment]
@jancassio "node_modules" is the default value. referring from its doc.

[https://webpack.js.org/configuration/resolve/#resolve-modules](https://webpack.js.org/configuration/resolve/#resolve-modules)

I guess if you remove it, webpack won't be able to find JS files in node_modules directory.

**Comment by jancassio** [comment]
@kemhwd Ok, seems this makes things more clear

>> If you want to add a directory to search in that takes precedences over node_modules/:
    modules: [path.resolve(__dirname, "src"), "node_modules"]

**Comment by jarecsni** [comment]
Thanks to @MartanLV I managed to fix my issue. In my case a stupid typo compounded the issue. To be honest, webpack could be better at emitting useful error messages. Saying that an alias cant be found is as useful as saying 'something's wrong'

**Comment by ThePadawan** [comment]
@jarecsni By googling lots and lots of webpack errors without a useful error messages, I discovered the great flag "--display-error-details" which actually helps a lot. It displays a boatload of error details that actually help quite often. HTH.

**Comment by rossjp** [comment]
I recently stumbled onto a solution that works for me. If you're using Typescript 2.0+ (which you should be) and `awesome-typescript-loader` (which you should be) you can obviate the need for `resolve.alias` by using the tsconfig parameters `baseUrl` and `paths` inside of the top-level `compilerOptions` parameter. It's great because it works regardless of how you manage your modules and if you're using a linter (which you should be) will automatically be understood. Here's an example from my code: 

```
"compilerOptions": {
  ...
  "baseUrl": ".",
  "paths": {
    "@Client/*": ["client/*"],
    "@Components/*": ["client/src/components/*"],
    "@Containers/*": ["client/src/containers/*"],
    "@Repository/*": ["server/src/repository/*"],
    "@Server/*": ["server/*"],
    "@Shared/*": ["shared/*"]
  }
  ...
}
```

To allow webpack to access these aliases, add the following `require` and also add the following `plugins` configuration to your webpack config's `resolve`: 

```
const { TsConfigPathsPlugin } = require('awesome-typescript-loader');
```

```
resolve: {
  ...
  plugins: [
    new TsConfigPathsPlugin(/* { tsconfig, compiler } */)
  ],
  ...
},
```

Now, when you want to import something from the `{projectDir}/shared` directory you can reference it like this: 
`import { MyType, MyInterface } from "@Shared/types";`

🎉

**Comment by theGC** [comment]
I just hit an issue which caused all aliases to stop resolving due to the me adding a second `package.json` file within one of the src directories.

This error was thrown up in the eslint feedback and it seems to be further related to the use of `eslint-import-resolver-webpack` to resolve imports within my src files.

A rather specific use case but thought it may help some shed a little light on things.

**Comment by philayres** [comment]
In case anybody using Rails with webpack runs across this, the place to put in an alias for @ paths is:

    config/webpack/shared.js

Just add to the `resolve:` hash:

      alias: {
           '@': resolve(settings.source_path + '/packs'),
      },

**Comment by cheerly** [comment]
@raminiousbug

**Comment by cheerly** [comment]
thanks

**Comment by ZhuJingSi** [comment]
don't use eslint-loader and everything will be ok

**Comment by hongzzz** [comment]
I fixed it by removing `node_modules`  and run `npm install`

**Comment by stereokai** [comment]
This happens to me with Webpack 3

**Comment by koshevy** [comment]
Same issue: I using latest webpack with Angular4 and added some fast paths via `resolve.alias` and got errors:

```
ERROR in [at-loader] ./src/app/app.module.ts:39:8 
    TS2307: Cannot find module 'core'.

ERROR in [at-loader] ./src/app/app.module.ts:47:8 
    TS2307: Cannot find module 'shared/layouts'.

ERROR in [at-loader] ./src/main.browser.aot.ts:10:36 
    TS2307: Cannot find module '../compiled/src/app/app.module.ngfactory'.
Child html-webpack-plugin for "index.html":
```

But I was wondered that it's eventually works despite the error.  I sent to log obtained objects in place where those errors have been appeared:

```
import {
  RootErrorHandler,
  LoggerService
} from 'core';

import {
  APP_LAYOUTS_DECLARATIONS
} from 'shared/layouts';

console.log('>>> LoggerService:', LoggerService);
console.log('>>> APP_LAYOUTS_DECLARATIONS:', APP_LAYOUTS_DECLARATIONS);
```

And got properly output in my browser:

```
>>> LoggerService: ƒ LoggerService(http) {
        this.http = http;
    }
>>> APP_LAYOUTS_DECLARATIONS: (2) [ƒ, ƒ]
```

And application starts and working without any errors. What it's means? The error in some loader or plugin?

**Comment by koshevy** [comment]
Update, excuse me. It seems, it s not WebPack problem but  problem of 'awesome-typescript-loader' in my case.

**Comment by ncjones** [comment]
For me this issue was triggered when changing the Webpack context. By setting the Webpack context to the src dir, aliases **DO NOT** work:

```js
// webpack.config.js:
module.exports = {
  context: path.resolve(__dirname, './src'),
  entry: {
    app: ['./index.js']
  }
  // ...
}
```

When using the root of the project as the Webpack context, aliases **DO** work:

```js
// webpack.config.js:
module.exports = {
  context: path.resolve(__dirname, '.'),
  entry: {
    app: ['./src/dashboard/index.js'],
  }
  // ...
}
```

**Comment by bauer01** [comment]
I can confirm that the problem is connected with using custom context in my case too

**Comment by tugayilik** [comment]
I resolved the issue by doing join, instead of resolve

```jsx
alias: {
    Ui: path.join(__dirname, '/resources/assets/js/ui/'),
}
```

**Comment by imam** [comment]
@tugayilik It's working. May I ask you to explain why is it making any difference? I'm curious

**Comment by tugayilik** [comment]
@imam According to node.js documentation;

Simply how **resolve** works;

`path.resolve('/foo', '/bar')` _outputs /bar_

This will always result in absolute url, simply passing __dirname as first argument doesn't matter in this case. Calling path.resolve() without any argument will give you __dirname.

According to my example, if i want to use path.resolve i need to use it like `path.resolve('resources/assets/js/ui/')`. It outputs `__dirname/resources/assets/js/ui`

How **join** works is simple, it brings all given arguments together and and gives you to path string;

`path.join(__dirname, '/foo')` _outputs_ ___dirname/foo_

**Comment by joe223** [comment]
I got the same issues 
```javascript
resolve: {
    alias: {
      'create-api': './create-api-client.js',
      'modules': path.resolve(__dirname, '../node_modules')
    }
  },
```
`modules` is not working，
this is Error message
```
// import pinyin from 'modules/pinyin/dist/bundle.js'

Module not found: Error: Can't resolve 'modules/pinyin/dist/bundle.js' in '/Corvette/src/lib'
```

**Comment by TimMeade** [comment]
After reading and trying most of the options here this worked from me:   @tugayilik got it....

      Containers: path.resolve('src/containers/'),
      Components: path.resolve('src/components/'),

What worked here.

**Comment by Sawtaytoes** [comment]
I've been having this issue for the last hour trying all sorts of different combinations.

_**NOTE:** This works fine when using `modules`, but `alias` is where I see the issue._

I'm on windows and have my Webpack config in a different directory than my project root and my project is on my secondary `D:` drive. The path I'm sending in is absolute:
```
D:\Projects\Companies\[PROJECT_NAME]\app
```

Webpack config:
```js
{
	resolve: {
		alias: {
			'~': 'D:\Projects\Companies\[PROJECT_NAME]\app',
		},
		extensions: ['.js'],
		modules: ['node_modules'],
	},
}
```

In a component, I import like this:
```js
import Sample from '~/components/samples/Sample'
```

I receive this error:
>ERROR in ./app/entrypoints/client/index.js
Module not found: Error: Can't resolve '~/components/samples/Sample' in 'D:\Projects\[PROJECT_NAME]\app\samples\Sample'

**Comment by adeperio** [comment]
Yep same, still getting this issue too. Doesn't seem to work at all

**Comment by Sawtaytoes** [comment]
I was able to resolve this issue on my end.

I was merging Webpack config objects and was accidentally overriding an undefined alias prop with the one that had data.

**Comment by adeperio** [comment]
As a work around I've used webpack.Define plugins to get environment specific config. That seems to be working pretty well. I pass the environment through a command line parameter when running or building. I then use that to import a .json file with specific environment settings. Hope someone finds that useful too...

`
module.exports = env => {

  var config = require(`../config/${env}.json`)

  return {
    ...

    plugins: [
      new webpack.DefinePlugin({
        'env': JSON.stringify(config)
      })
    ]
  };
};
`

**Comment by kemalcany** [comment]
Hello everyone

I had a problem with resolving files outside my project directory. It worked for some files and didn't work for others like @aryzing mentioned above..

I just managed to solve this problem with a simple edit: putting a @ character in front of the alias...

Before it was
`config.resolve.alias['global'] = path.join(__dirname, '../_global')`

Now it is
`config.resolve.alias['@global'] = path.join(__dirname, '../_global')`

And it works..

Hope this will help others

**Comment by aryzing** [comment]
> Adding @ in front of the alias name solve the issue

Why? Where is this documented?

**Comment by kemalcany** [comment]
@aryzing i couldn't find any documentation. just did a random experiment and it worked 🥇

**Comment by tugayilik** [comment]
@Cedric1994 I think your problem was; your alias `common`  has the same name with the existing directory `common`. The solution was not `@`at the beginning, it was different name than `common`.

**Comment by vasivas** [comment]
Didn't work either. added aliases to the preprocessor config, worked!

**Comment by matthewmueller** [comment]
One thing that tripped me up is that **aliases are ordered**.

**wrong order:**

```js
const aliases = {
  preact: require.resolve('preact'),
  'preact/devtools': require.resolve('preact/devtools'),
}
```

**right order:**

```js
const aliases = {
  'preact/devtools': require.resolve('preact/devtools'),
  preact: require.resolve('preact')
}
```

You'll want to have your more specific aliases come before more general aliases.

**Comment by Rutulpatel7077** [comment]
Not a single solution worked from this discussion for [@React](https://reactjs.org/)

**Comment by EmilyRosina** [comment]
I have not found a solution yet, but this occurs in all new Vue-CLI projects - works in my older ones...

This is (at least for me) down to the addition of using `@Types` in my node modules, I guess Vue uses this now.. but i'm in the middle of trying to solve this without pulling my hair out. It is interesting to know that `@Babel` does not trip up the use of `@` aliases within paths...

Thought it was one/two of my VS-Code extensions for intellisense paths, but that turned out to be a red herring.

**Comment by ralphsmith80** [comment]
I forked `create-react-app` so I could add support for importing some previously created bower components. We've proven this works with a minimal webpack config but we want to create our app with `create-react-app` so we can get all the `react-script` goodness. 

The only thing that's problematic is resolving our aliases. No idea why this isn't working. There is a single bower component that has a `vendor` directory. The alias definition looks as follows.

Alias:
```
backbone: path.resolve(__dirname, 'glu/vendor/backbone/backbone')
```

Error:
```
./bower_components/glu/model.js
Module not found: Can't resolve 'backbone' in '/Users/ralph.smith/Workspace/bfs/bower_components/glu'
```

What's kind of interesting is if I remove the alias and add a module definition: 
```
 modules: ['node_modules', paths.appNodeModules, 'bower_components', 'glu/vendor']
```

The above error goes away but I get other errors for things in the vendor directory:
```
./bower_components/glu/appBus.js
Module not found: Can't resolve 'backbone.wreqr' in '/Users/ralph.smith/Workspace/bfs/bower_components/glu'
```

**Comment by ralphsmith80** [comment]
I solved my alias problem by using the `resolveApp` utility in `react-scripts/config/path.js`.

e.g.

```
const appBowerModules = resolveApp('bower_components')
const gluVendor = resolveApp('bower_components/glu/vendor')

// put this in the webpack alias array
const alias = {
  backbone: path.resolve(appBowerModules, gluVendor, 'backbone/backbone'),
}
```

**Comment by milangupta511** [comment]
Any working solution for this?

**Comment by Rutulpatel7077** [comment]
@milangupta511 Please specify your issue again. It could be different but Yes! Since I know this issue is resolved.

**Comment by manuelro** [comment]
Given the following folder structure:

```
~/src/components
```

**Storybook Webpack config**

`.storybook/webpack.config.js`
```
module.exports = {
  resolve: {
    alias: {
      '@components': path.resolve('src/components/')
    }
  }
};
```

**Your component**

`~src/components/Button.js`
```
import React from 'react'

export default ({ children, ...rest }) => (
  <button {...rest}>{children}!!!</button>
)
```

**Storybook stories**
`index.stories.js`
```
import React from 'react';

import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';

import Button from '@components/Button'

storiesOf('Button', module)
  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
  .add('with some emoji', () => (
    <Button onClick={action('clicked')}>
      <span role="img" aria-label="so cool">
        😀 😎 👍 💯
      </span>
    </Button>
  ));
```

It should work. 😎

**Things to notice**

Exports/Imports 
`import { Button } from '@components/Button'` != `import Button from '@components/Button'`

**Comment by manuelro** [comment]
Given the following folder structure: `~/src/components/Button.js`

**Storybook Webpack config**
`~/.storybook/webpack.config.js`
```
module.exports = {
  resolve: {
    alias: {
      '@components': path.resolve('src/components/')
    }
  }
};
```

**Your component**
`~/src/components/Button.js`
```
import React from 'react'

export default ({ children, ...rest }) => (
  <button {...rest}>{children}!!!</button>
)
```

**Storybook stories**
`~/stories/index.stories.js`
```
import React from 'react';

import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';

import Button from '@components/Button'

storiesOf('Button', module)
  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
  .add('with some emoji', () => (
    <Button onClick={action('clicked')}>
      <span role="img" aria-label="so cool">
        😀 😎 👍 💯
      </span>
    </Button>
  ));
```

It should work. 😎

**Things to notice**
Exports/Imports 
`import { Button } from '@components/Button'` != `import Button from '@components/Button'`

**Comment by javadbat** [comment]
@Sawtaytoes  can you explain more what you do? I'm stuck so bad in making static path

**Comment by Sawtaytoes** [comment]
@javadbat 

In my Webpack config, I have this:
```js
  resolve: {
    alias: {
      '@shared': path.dirname(require.resolve('app')),
      '~': path.join(fs.realpathSync(process.cwd()), 'app'),
    },
    extensions: ['.js'],
    modules: [paths.nodeModules],
  },
```

All of my browser code is in the `app/` directory. This particular project has a differentiation between a package's `app/` folder and the current project's `app/` folder.

In this example, `@shared` is the package, `~` is the project. I wouldn't do it this way in the future, but I know this configuration works.

**Comment by jpdevries** [comment]
Aliases are absolute nonsense for resolving imports. If you don't want to type `../` consider using something like `path.resolve(__dirname, '../src')` so you can do

```js
import Stuff from 'client/components/stuff'; // relative to root of project
```
instead of:
```js
import Stuff from 'COMPONENTS/stuff'; // this is dumb
```
or:
```js
import Stuff from './../stuff; // once upon a time highly paid web devs didn't complain about relative paths now they do
```

**Comment by aprilmintacpineda** [comment]
I think `alias` is broken or maybe the documentation needs to explain it better.

```js
resolve: {
      alias: {
        _self: path.join(__dirname, 'src/web'),
        _shared: path.join(__dirname, 'src/shared'),
        _components: path.join(__dirname, 'src/web/components'),
        _helpers: path.join(__dirname, 'src/web/helpers'),
        _layers: path.join(__dirname, 'src/web/layers'),
        _mutations: path.join(__dirname, 'src/web/mutations'),
        _routes: path.join(__dirname, 'src/web/routes')
      }
    }
```

```js
import { something } from '_components';
```

RESULT:

```
"export 'something' was not found in '_components'
```

But it's in the `components/index.js`, if I do normal relative import it works fine. I also think it does not understand `export * from './module';` and `export {default as something} from './module';`.

**Comment by alexeychikk** [comment]
Your problem might be that you have your webpack config in some nested folder, f.e.: 
`project-name/configs/webpack/dev.js`
Then you would need something like this:
```javascript
const srcDir = path.resolve(__dirname, '../../src'); // resolve project src directory

module.exports = {
	resolve: {
		alias: {
			'@components': path.join(srcDir, 'components'),
			'@modules': path.join(srcDir, 'modules'),
			'@store': path.join(srcDir, 'store')
		}
	}
       //...
}
```

This worked for me.

**Comment by aprilmintacpineda** [comment]
@alexeychikk my webpack config is on the root directory, the import I'm aliasing though is OUTSIDE the directory of where the entry file is located, it's one directory up.

My directory looks like this:

```
/ root
| -- src
|     | -- web
|     ` -- shared
| -- webpack.prod.js
```

But I assumed it does not matter where the folder is located since the alias is specifically directed to that folder via `_shared: path.join(__dirname, 'src/shared')`

So doing something like this should work:

```
import SomeModule from '_shared/someModuleDirectoryWithIndexJSinIt';
import { anotherModule } from '_shared/directory/anotherModuleDirectoryWithIndexJSinIt';
```

Unless there's a reason it shouldn't. `console.log`s show that there's no problem with the paths. I can also verify that the aliased paths are being looked up because when I remove the `alias`es I get a different error. If I take @aryzing's advice, I would get an error complaining about my webpack config:

```
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
       ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
```

**Comment by aprilmintacpineda** [comment]
Here's a repo where you can see this being used and work -->  [webpack-multi-build-template](https://github.com/aprilmintacpineda/webpack-multi-build-template).

**Comment by asos-oliverwilson** [comment]
Not having any success with achieving this in a react project.

**Comment by aprilmintacpineda** [comment]
@asos-oliverwilson how did you instantiated that react project? via create-react-app?

**Comment by AnthonyLenglet** [comment]
Had an alias issue with tsx files, turns out that path.resolve was indeed the fix on my end

what used to be
```js
'#': './src/'
```
is now
```js
'#': path.resolve('src/')
```

**Comment by Tech-Nomad** [comment]
Also for me the issue was the "./".
After removing it from the path Webpack finally resolves the alias!! 🎉
(Actually I am using Encore but the it should be the same for pure Webpack config)

`let config = Encore.getWebpackConfig();
config.resolve.alias["~"] = path.resolve(__dirname, 'assets/js');
module.exports = config;`

**Comment by evenfrost** [comment]
In case someone runs into similar issue when using CSS modules via [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules), here's my solution: https://github.com/gajus/babel-plugin-react-css-modules/issues/25#issuecomment-478661715.

**Comment by BonBonSlick** [comment]
```
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: {
            // vue: 'vue/dist/vue.esm.js',
            config: path.resolve(__dirname, '../config'),
            vue: 'vue/dist/vue.js',
            // vue: 'vue/dist/vue.js',
            // 'vue$': 'vue/dist/vue.common.js',
            src: path.resolve(__dirname, '../src'),
            store: path.resolve(__dirname, '../src/store'),
            assets: path.resolve(__dirname, '../src/assets'),
            components: path.resolve(__dirname, '../src/components'),
            '@': path.resolve(__dirname, '../src'),
        },
    },
```
`
Module not found: Error: Can't resolve '@/store/modules/public/common/getters' in 
`

```

    "webpack-bundle-analyzer": "^3.4.1",
    "webpack-cli": "^3.3.6",
    "webpack-dev-server": "^3.8.0",
    "webpack-merge": "^4.1.4"
```

**Comment by renatoargh** [comment]
I still have this problem when I have nested alias, for example:

```js
 '@graphql-schema/order': path.resolve('src/graphql-schemas/order/'), // doesn't work
 '@graphql-schema': path.resolve('src/graphql-schemas/'), // works
```

I thought that the second line would be enough to resolve imports like `import orderSchema from '@graphql-schemas/order/schema';` but I get `Module not found: Error: Can't resolve '@graphql-schemas/order/resolvers' in '/my-app/src/graphql'`

:(

**Comment by evilebottnawi** [comment]
@renatoagds can you create minimum reproducible test repo?

**Comment by renatoargh** [comment]
I am sorry @evilebottnawi just realized it was a problem on my side, please disregard.

**Comment by evilebottnawi** [comment]
Issue should be solved, but some loaders can't support `alias` so need improve them, i am closing this issue due a lot of comments with spam like `:+1`, `Same issue` and etc, it is not help to solve issue so feel free to open new issue with reproducible test repo if you have problems

**Comment by kkjdaniel** [comment]
> I've given up on this for now and just started using `babel-plugin-module-resolver` because I'm already using babel anyway. That allows me to create the same type of aliases through a babel transform.

I haven't been able to get `resolve.alias` to work. At the time of writing I am using `"webpack": "4.19.1"`.

I have instead opted to use `babel-plugin-module-resolver` and this seems to be working great. Definitely an alternative if like myself you have spent far too long bashing your head against the wall!

**Comment by dudewad** [comment]
> Aliases are absolute nonsense for resolving imports. If you don't want to type `../` consider using something like `path.resolve(__dirname, '../src')` so you can do
> 
> ```js
> import Stuff from 'client/components/stuff'; // relative to root of project
> ```
> 
> instead of:
> 
> ```js
> import Stuff from 'COMPONENTS/stuff'; // this is dumb
> ```
> 
> or:
> 
> ```js
> import Stuff from './../stuff; // once upon a time highly paid web devs didn't complain about relative paths now they do
> ```

This is not dumb _at all_. It is exceedingly common to use aliases. It's not about being lazy, it's about writing portable code.

**Comment by danielstern** [comment]
I'm still getting this issue in version 4.29.6.

**Comment by andyl** [comment]
A new decade has arrived - this still does not work.  Latest Webpack4.

**Comment by leefsmp** [comment]
+1 works nada amigos

**Comment by daamdaam** [comment]
+1 rien copains

**Comment by Mateiadrielrafael** [comment]
still doesnt work

**Comment by bobber205** [comment]
Having this issue when trying to use **Option 3**  when configuring `node-env` for Webpack (https://github.com/lorenwest/node-config/wiki/Webpack-Usage)
