### ISSUE TITLE
Code-splitting creates request for "undefined.js" 404

### ISSUE THREAD

**Issue by syranide** [webpack/webpack#433]
Using version `webpack@1.3.7`

I've started using code-splitting and it seems `webpack --watch` start outputting broken bundles as soon as I make a change to any file, it's fixed by just restarting the process (which makes watching pointless).

Chrome outputs the following error to the console:

```
GET http://.../static/undefined.js 404 (OK)
```
```
output: {
  path: '/...',
  filename: 'static/[name].js',
  chunkFilename: 'static/[chunkhash].js'
}
```

I'm assuming `[chunkhash]` for some reason become `undefined` when it's rebuilding the bundle.

PS. The terminal does not seem to print any errors and the bundle is correctly named there:

```
              static/bundle.js   379082       1  [emitted]  bundle
static/b8585b0346bbe807fec7.js  1291905       2  [emitted]
```

**Comment by tazsingh** [comment]
@syranide I'm facing this same issue with my webpack configuration and `OccurrenceOrderPlugin` which I need in order to keep the `chunkhash`es consistent across webpack builds. What was your final solution for this?

**Comment by syranide** [comment]
@tazsingh I simply stopped using that plugin in watcher builds and as I mention above, since the new watcher plugin became standard I haven't seen this issue again (still not using OccurenceOrderPlugin with watcher though)... but yeah, the underlying problem is most likely still there.

**Comment by tazsingh** [comment]
Ok thanks @syranide. Unfortunately that solution does not work for me.

I have to use the `OccurrenceOrderPlugin` as without it the order of modules changes in the chunks for every build and therefore affects the `chunkhash`es across deploys.

I also note that for the chunk with id of `0`, the chunkhash is `undefined`, and those modules seem to have issues loading both in development and production.

Would you mind re-opening this issue since the problem is still there? Not sure if you can somehow transfer the issue over to me but I'm also happy to open another one if that's easiest.

**Comment by syranide** [comment]
@tazsingh Use OccurrenceOrderPlugin when deploying, don't use it when in dev-watcher mode, that's what I do (not an actual fix, just saying :)).

**Comment by tazsingh** [comment]
@syranide Aye I tried that but the `chunkhash`es are still different between builds which is the issue I need `OccurrenceOrderPlugin` for :( Also doesn't fix that modules for id `0` chunkhash `undefined` aren't loading in production and only load the 1st time in development.

Looking at the module itself, it's pretty small and I'm going to try to debug myself when I have a moment. Unless someone gets to it before I do ;)

**Comment by GVRV** [comment]
Bump! 

I'm getting this error as well. My config looks like the following: 

```
output: {
        path: path.join(__dirname, '/static/js-build'),
        publicPath: '/static/js-build/',
        filename: '[name].js',
        chunkFilename: '[name].[chunkhash].js'
    },
    plugins: [
        new webpack.optimize.OccurenceOrderPlugin(true),
        new CommonsChunkPlugin({
            name: 'loader',
            async: true,
            children: true,
            minChunks: 4
        }),
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            'windows.jQuery': "jquery",
            'window.jQuery': 'jquery',
            'utils': 'base/utils',
            '_': 'underscore'
        })
    ],
```

When I run `watch` for the first time, I'm seeing the following:

```
script.src = __webpack_require__.p + "" + ({}[chunkId]||chunkId) + "." + {"0":"bc0f416c243586a39305","1":"5e140bbde4840d666c6d","2":"40544ca1dbd79368893f","3":"577e6158bc5b1ba12587","4":"c6482bcfd471e74c7676","5":"af301f6257f03c63f00b","6":"88640629f921d19d0eab","7":"e25843054d9cd8a0abea","8":"35aa9c30ba5896a495db","9":"dfcb649d38a68d48ddc7","10":"bf1dccfd400bb6c61fc6","11":"d5c96579dc8c2fd6a864","12":"71dce135550408d62e31","13":"fa078e210d425cd6130d","14":"98a66b432bb3044de94d","15":"6cad74a12081d77ea577","16":"cbb81e02701ec14a2586","18":"0f6ac204e422f6928184","19":"0343ac43a2de3582fac5","20":"a9927efe45dde53eee7f","21":"ef16ad31bdbecd7adc85","22":"ad42ba066246249558f0","23":"d13817314b227b83cf0f","24":"7a597ded855705002760","25":"19e811a3da4c28275de2","26":"3e8669acf09da7bc6428","27":"70ba7cbcc8a2e326ffb1","28":"512bd2655e2aa70aae69"}[chunkId] + ".js";
```

which works because I have calls like the following in my entry point: 

```
var loaderChain = {
	        base : {
	            init : function() {
	                (function(/* nsure */) {var __WEBPACK_REMAINING_CHUNKS__ = 2;var __WEBPACK_CALLBACK__ = function() {if(--__WEBPACK_REMAINING_CHUNKS__ < 1) (function() {
	                    k3.base = __webpack_require__(7);
	                    // We load the non-cart module every except in the cart app, the orders app and on the product upsell view.
	                }(__webpack_require__));};__webpack_require__.e(0, __WEBPACK_CALLBACK__);__webpack_require__.e(5, __WEBPACK_CALLBACK__);}());
	                if(!document.body.className.match(/k3_cart_app|k3_orders_app|product_upsell_view|kb_v2_app|knowledge_base_app/)){
	                    (function(/* nsure */) {var __WEBPACK_REMAINING_CHUNKS__ = 2;var __WEBPACK_CALLBACK__ = function() {if(--__WEBPACK_REMAINING_CHUNKS__ < 1) (function() {
	                        k3.noncart = __webpack_require__(27);
	                    }(__webpack_require__));};__webpack_require__.e(0, __WEBPACK_CALLBACK__);__webpack_require__.e(11, __WEBPACK_CALLBACK__);}());
	                }
	            }
	        },
``` 

Now, when I edit any watched file, the calls above remain the same, but the hash mapping updates itself to something like: 

```
script.src = __webpack_require__.p + "" + ({}[chunkId]||chunkId) + "." + {"1":"5e140bbde4840d666c6d","2":"40544ca1dbd79368893f","3":"577e6158bc5b1ba12587","4":"c6482bcfd471e74c7676","5":"af301f6257f03c63f00b","6":"88640629f921d19d0eab","7":"e25843054d9cd8a0abea","8":"35aa9c30ba5896a495db","9":"dfcb649d38a68d48ddc7","10":"bf1dccfd400bb6c61fc6","11":"d5c96579dc8c2fd6a864","12":"71dce135550408d62e31","13":"59028756d0060c9c9cf4","14":"98a66b432bb3044de94d","15":"6cad74a12081d77ea577","16":"cbb81e02701ec14a2586","18":"0f6ac204e422f6928184","19":"0343ac43a2de3582fac5","20":"a9927efe45dde53eee7f","21":"ef16ad31bdbecd7adc85","22":"ad42ba066246249558f0","23":"d13817314b227b83cf0f","24":"7a597ded855705002760","25":"19e811a3da4c28275de2","26":"3e8669acf09da7bc6428","27":"70ba7cbcc8a2e326ffb1","28":"512bd2655e2aa70aae69","29":"af325657af5dee52815c"}[chunkId] + ".js";
```

Note that `0` is now missing as a key from the above hash mapping and that might be reason I'll now be getting a `GET` for `0.undefined.js` every time a call like `__webpack_require__.e(0, __WEBPACK_CALLBACK__);` is made. I'm guessing the hash mapping is getting updated without the actual calls being updated (or something like that — I couldn't track deeper as I got lost navigating the repo). I hope this information helps you to nail down what is causing this most annoying bug.

**Comment by sokra** [comment]
@GVRV Thanks for the detailed report. Unfortually I'm still not able to reproduce it :(. Does it only occur with the `CommonsChunkPlugin`? Does it only occur with the `OccurenceOrderPlugin`?

**Comment by psimyn** [comment]
@sokra I am able to replicate in the [extra-async-chunk](https://github.com/webpack/webpack/tree/master/examples/extra-async-chunk) example with the following config:

```
var path = require("path");
var webpack = require("webpack");
var CommonsChunkPlugin = require("../../lib/optimize/CommonsChunkPlugin");
var OccurenceOrderPlugin = require("../../lib/optimize/OccurenceOrderPlugin");

module.exports = {
  entry: {
      'main': ['./example']
  },
  output: {
    path: path.join(__dirname, '/out'),
    filename: '[name].js',
    chunkFilename: '[name].[chunkhash].js'
  },
  plugins: [
    new OccurenceOrderPlugin(true),
    new CommonsChunkPlugin({
        name: "main",
        async: true,
        minChunks: 2
    })
  ]
};
```

- Running ```webpack --watch``` outputs main.js and 3 chunks (0.js, 2.js, 3.js).
- Subsequent builds add 4.js with the contents of 0.js
- main.js still tries to require.ensure a chunk with chunkId of 0

Removing either 'async', OccurenceOrderPlugin, or [chunkhash] from chunkFilename prevents the issue

**Comment by sokra** [comment]
@psimyn thanks. I identified the problem. Async extra chunks are not recorded correctly and get a new id in every compilation.

**Comment by sokra** [comment]
I hope it's fixed now...

**Comment by GVRV** [comment]
@sokra Thanks for the quick patch! We'll test it out and report back.

**Comment by psimyn** [comment]
fixed, thanks @sokra!

**Comment by syranide** [comment]
:+1:

**Comment by zemlanin** [comment]
Got the same problem but with `webpack.js@2.2.1` — one of two entries requests `/dist/1-undefined.js` (example repo https://github.com/zemlanin/dynamite)

```js
// webpack.config.js
const path = require('path')
const webpack = require('webpack')

module.exports = {
  entry: {
    main: './main.js',
    pain: './pain.js',
  },
  output: {
    filename: '[name].js',
    chunkFilename: '[id]-[chunkhash].js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'dist/',
  },
  module: {
    rules: [{
      test: /\.js$/,
      exclude: /(node_modules)/,
      use: [{
        loader: 'babel-loader',
        options: {
          presets: [['es2015', {modules: false}]],
          plugins: ['syntax-dynamic-import']
        }
      }]
    }]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      names: ['main', 'pain'],
      async: true,
      minChunks: (module, count) => /node_modules/.test(module.userRequest),
    }),
  ],
}
```

```bash
$ npm run webpack -- --hide-modules; grep 'script.src = __webpack_require__.p' dist/pain.js dist/main.js
...
Version: webpack 2.2.1
Time: 903ms
                    Asset       Size  Chunks             Chunk Names
0-fdfde16e569cd099cda0.js  650 bytes       0  [emitted]  
1-697132204232dcb21be2.js    30.4 kB       1  [emitted]  
2-6521e81a926120e1048d.js    1.56 kB    2, 3  [emitted]  
3-eaee5cac6bd576a1a204.js    1.07 kB       3  [emitted]  
                  pain.js    20.9 kB       4  [emitted]  pain
                  main.js    21.3 kB       5  [emitted]  main
dist/pain.js:/******/ 		script.src = __webpack_require__.p + "" + chunkId + "-" + {"0":"fdfde16e569cd099cda0"}[chunkId] + ".js";
dist/main.js:/******/ 		script.src = __webpack_require__.p + "" + chunkId + "-" + {"0":"fdfde16e569cd099cda0","1":"697132204232dcb21be2","2":"6521e81a926120e1048d","3":"eaee5cac6bd576a1a204"}[chunkId] + ".js";
```

**Comment by kazazor** [comment]
@zemlanin I'm also seeing this behavior with webpack 2 (I uses `2.3.3`).

I'm trying to make HMR work and everything seems ot be working fine expect for the fact that the async chunks (when uses `syntax-dynamic-import`) gets new id & chunkhash after the second compile.

I also tried using `recordsPath` even that webpack-dev-server uses that in memory, still no luck.

This is how I set my names:
```js
    filename: '[name]-[chunkhash].js',
    chunkFilename: '[name]-[chunkhash].js'
```

A temporary solution would just be dropping the `[chunkhash]` in development and just keep the `[name]`.

@sokra - any chance this is a regression with webpack 2? If so, can this issue be reopen / open a new issue for webpack 2?

**Comment by kazazor** [comment]
Well actually everything started working for me after I added
```
new webpack.NamedModulesPlugin()
```

In the docs this is described as a suggestion, and here it seems without it nothing works. Maybe a change in the docs is required or I'm missing something here.

**Comment by sokra** [comment]
Could you create a new issue?

**Comment by kazazor** [comment]
Done: https://github.com/webpack/webpack/issues/4719
