### ISSUE TITLE
Bug in uglify-js leads to broken build (Invalid left-hand side expression in postfix operation)

### ISSUE THREAD

**Issue by dahei** [webpack/webpack#4394]
Because it caused me some headaches the last hour:

If your (optimized via UglifyJsPlugin) production build stopped working and the console in chrome says 

```
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation
```

It's most likely this bug:

https://github.com/mishoo/UglifyJS2/issues/1516

As hotfix you can nail the uglify-js version in your package.json to 2.7.5 and reinstall your node_modules.

**Comment by TeChn4K** [comment]
I was getting completely crazy... Thanks for the information

**Comment by bebraw** [comment]
Note that there's a [standalone version](https://www.npmjs.com/package/uglifyjs-webpack-plugin) of the core plugin that makes it easy to control the version of Uglify.

**Comment by FuKe** [comment]
Thanks for the hotfix, this bug has been troubling me for the last couple of hours..

**Comment by cristian-sima** [comment]
Any quick-hot-fix for a production version that I already deployed?

**Comment by dahei** [comment]
@cristian-sima 

Can't imagine how that could be accomplished as your deployed code is already broken. I think there is no other way than re-deploy.

Note: there will be a hotfix-update:

https://github.com/mishoo/UglifyJS2/issues/1516#issuecomment-283085025

But that doesn't fix your currently deployed version.

**Comment by cristian-sima** [comment]
@dahei I mean that I can re-deploy a new generated version, but quick as people did not realise the problem.

Waiting for the hotfix.

By the way, I am amazed by the live community that reacted to this problem.

**Comment by bebraw** [comment]
@cristian-sima To avoid surprises in the future, please maintain a lockfile (far harder to break). I linked to a plugin where you can control uglify version so that may help too.

**Comment by cristian-sima** [comment]
thanks @bebraw

**Comment by sokra** [comment]
uglify-js@2.8.1 fixes it

It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by alexaivars** [comment]
Since you closed the issue I just want to say we still have issues with webpack@2.2.1 & uglify-js@2.8.1 combo. Downgrading to webpack@2.2.0 & uglify-js@2.8.1 which fixed the problem until we can investigate further.

**Comment by bebraw** [comment]
@alexaivars You could try the fix proposed at #4398 with 2.2.1. I wonder what changed between 2.2.0 and 2.2.1, though.

**Comment by alexaivars** [comment]
@bebraw Thank's will have a loog att #4398 but will have to investigate further to have som useful feedback. Just wanted to give a headsup.

**Comment by sarn3792** [comment]
Did you find a solution? 
How can I solve it?

**Comment by cristian-sima** [comment]
@sarn3792 
They released a new version of `UglifyJS2` ```2.8.1 ``` where the bug is fixed.

See Dan's comment https://github.com/mishoo/UglifyJS2/issues/1516#issuecomment-283091573

The **solution** is to update your packages. 
# Change inside the `package.json` the `UglifyJS2` to version `2.8.1`.

Hope this helps
