### ISSUE TITLE
ionic build takes long on webpack > 3.6.0

### ISSUE THREAD

**Issue by dmastag** [webpack/webpack#5876]
**Do you want to request a *feature* or report a *bug*?**
I want to report a Bug

**What is the current behavior?**
If using webpack that is higher than 3.6.0 than my Ionic Build is taking much longer
https://github.com/ionic-team/ionic-app-scripts/issues/1280

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a new Ionic App and use webpack above 3.6.0

**What is the expected behavior?**
My normal build takes around 2 minutes while my production build takes 12 minutes
After upgrading my production build takes around 26 minutes

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I tested this on Webpack Version 3.7.0, 3.7.1 and 3.8.0 on a Windows 10 Machine

Something I noticed in my Task Manager is that on Webpack 3.6.0 node.exe memory usage can go up to 1.4GB. 
But on the newer ones its goes to a maximum of 830MB then drops to 750MB, and this keeps happening (I waited until 30 minutes for ionic serve)

**Comment by sokra** [comment]
Did you try 3.8.1? It should be fixed there.

**Comment by dmastag** [comment]
Thanks
Just tried it out and have the same problem

ionic serve takes a long time and in windows Task manager the amount of memory does not go above 750MB

![image](https://user-images.githubusercontent.com/5745805/32109963-7b3a9bd6-bb60-11e7-9eee-b794167e078f.png)

But on 3.6.0 it can go up to 1.3GB and is working in 2 minutes to load my app.

![image](https://user-images.githubusercontent.com/5745805/32110045-c2a8ea2c-bb60-11e7-894a-80f92f8c6e4f.png)

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by dmastag** [comment]
@sokra I tried that, but can't reproduce the issue on a fresh project
Is there any other way I could help out to show you ?
Maybe there is a debugger or something that i can turn on and send ?

**Comment by evilebottnawi** [comment]
@dmastag problem still exists? Can you try this with `webpack@4`?

**Comment by dmastag** [comment]
Sadly it does not solve it
Seems like ionic-app-scripts is not compatible with webpack 4
