### ISSUE TITLE
Runtime TypeError: Cannot read property 'call' of undefined at __webpack_require__

### ISSUE THREAD

**Issue by aaronbeall** [webpack/webpack#6094]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When I try to run my project with `webpack-dev-server` I get runtime error `Cannot read property 'call' of undefined` at `__webpack_require__`

**If the current behavior is a bug, please provide the steps to reproduce.**

Using this output configuration (which was working previously):
```js
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].[chunkhash].js',
    publicPath: '/',
    sourceMapFilename: '[file].map',
    chunkFilename: '[id].chunk.js'
  }
```
When I run `webpack-dev-server` using this command: 
```
cross-env NODE_ENV=development webpack-dev-server --progress -d --inline --host 0.0.0.0
```

I get a bunch of runtime errors that look like this:
```
vendor.356edb7e8753d46064d8.js:55 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (vendor.356edb7e8753d46064d8.js:55)
    at <anonymous>
```
If I remove the `chunkFilename`:
```js
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].[chunkhash].js',
    publicPath: '/',
    sourceMapFilename: '[file].map',
    // chunkFilename: '[id].chunk.js'
  }
```

Then it runs fine.

The entire config is here: https://gist.github.com/aaronbeall/b286eb3f2ff93bed37289f0fefbb3d3c

**What is the expected behavior?**

No error.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- webpack@3.10.0
- webpack-dev-server@2.9.7 
- node v8.6.0
- OSX 10.11.6

**Comment by agalatan** [comment]
I try not to combine **chunkhash** with something like **HotModulesReplacement** plugin or **webpack-dev-server**. In general, I try to use **chunkhash** only in Production. Also, we are told **not** to use those plugins in Production.

**Chunkhash**, from what I understand, is not updating correctly (on purpose or not, I don't know) when its content is changing. For safety, I consider it as being a constant, computed once and then never updated.

**Comment by evilebottnawi** [comment]
@aaronbeall `children: true` for `CommonsChunkPlugin` solve you problem?

**Comment by aaronbeall** [comment]
@evilebottnawi Thanks for reply... well currently I `children: true` in my second `CommonsChunkPlugin` instance:

```
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    minChunks(module, count) {
      return module.resource && module.resource.indexOf('node_modules') !== -1
    }
  }),
  new webpack.optimize.CommonsChunkPlugin({
    children: true,
    async: true,
    minChunks: 2
  })
```

To be honest I have no idea if this is a good or terrible idea, we initially used the `vendor` chunk then later added the `async` chunk to support dynamic route module loading. This *was* working until recently, afaik.

**Comment by hannadrehman** [comment]
removing dynamic imports fixed my issue

**Comment by Strate** [comment]
I made migration from require to import(), and got same problem

**Comment by EvHaus** [comment]
I've started to get this error fairly frequently after migrating to webpack 4.

**Comment by Neanstudio** [comment]
Constantly get this error when using dynamic imports. Even after updating Webpack to latest version (currently 4.3.0). Someone solved this problem (without removing dynamic imports)?

**Comment by salemhilal** [comment]
I don't have a general answer, but I have a few answers that are specific to my case that may help others debug. 

This happened to me twice, and each time was because of what was likely a misconfiguration rather than a bug in Webpack itself (as far as I can tell so far). Specifically, it seems to have happened because of a mismatch between modules expected to be loaded by a chunk file, and the modules _actually_ in that chunk file. I'm also still a bit rusty with terminology, so let me know if any of this doesn't make sense.

1. I have a custom server implementation that uses `webpack-dev-middleware`. I was inadvertently not re-building one of my entrypoints, but was still serving it statically (so, an old version of the file was being served). Additionally, the generated chunks were just named `[chunkId].js` (i.e. `1.js`, `2.js`, etc). This meant that it was requesting chunks by module ID that existed on disk, but were referring to different dependencies. Hence, a chunk would load, but the modules that were loaded from this chunk were _not_ what was expected. The fix for this was to rebuild the entry points that I had accidentally stopped building. 

2. I have multiple configs that all build to the same directory and chunks were overwriting each other across different builds because their names collided. This was fixed by naming the chunks based on`chunkHash` rather than by module name. Doing this would also probably make the problem I had above more obvious, since the names of the requested chunks would likely be different from the actual chunk files hosted by the server.

Not sure if that's useful or not, but I figure it may help someone else debug.

**Comment by ooflorent** [comment]
It would be great if someone could post a small reproducible example using webpack 4. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by alexdong** [comment]
I just sunk 3 hours into this issue. Removing dynamic import did fix my issue. 

I'm still on webpack `3.11.0`. This issue started happening after I upgraded from react `16.2` to `16.3` (with all the context API stuff.)  

My code structure looks like this. I have a component `UploaderToolbar` that contains multiple buttons, clicking on the instagram one will open up a `InstagramPicker`, which goes to download and display the photos via an array of `PhotoThumbnail` components.

`InstagramPicker` is dynamically loaded, through a thin wrapper called `HMLoadable`, using `react-loader 5.3.1`. 

```
// `uploader_toolbar.jsx`
const InstagramPicker = HMLodable({
  loader: () =>
     import(/* webpackChunkName: "instagram-picker" */ "./instagram_picker")
}); 
```

```
// `instagram_picker.jsx`
import PhotoThumbnail from "app-components/photo_thumbnail";
```

When the `UploaderToolbar` is imported on a page where `PhotoThumbnail` is already imported, it works just fine. Otherwise, it'd crash on this line: https://github.com/jamiebuilds/react-loadable/blob/v5.3.1/src/index.js#L199 and here is a screenshot.

![screenshot 2018-04-03 12 58 49](https://user-images.githubusercontent.com/190415/38223497-5a3ae21e-373f-11e8-8718-f70645abc6ec.jpg)

**Comment by ooflorent** [comment]
Once again, **please provide a small reproducible example**.

**Comment by maciej-gurban** [comment]
Not sure if that helps anybody, but I was getting the same error when changing the path of a dynamic import without shutting down and restarting the dev server.

I'd `import('./foo')`, but after I moved `./foo` to `./bar/foo` and changed the import to be `import('./bar/foo')` webpack would throw with `Cannot read property 'call' of undefined at __webpack_require__`.

Module `./foo` is wrapped with `hot` from `react-hot-loader`.

Restarting the dev server fixed the issue.

Some other info:
`webpack@4.2.0`, node dev server using `webpack-dev-middleware@3.0.1` and `webpack-hot-middleware@2.21.2`.

**Comment by YangDaniu** [comment]
The same problem when i run build with osx,bug it works well when i run dev.
and when i run build with window,it doesn't have the problem.

**Comment by lainiwakurafan** [comment]
Same problem here with webpack 4 when building assets in `production` mode.

When starting webpack-dev-server error was disappear.

PS. With webpack 3 works just fine.

**Comment by ganxunzou** [comment]
I have the same problem use `require.ensure`.  like @maciej-gurban Restarting the dev server is ok.

Description of my problem：
I have to router component, like:

```JS
require.ensure([], (require)=>{
  cb(null, require('./a').default)
},'abc')
```

```JS
require.ensure([], (require)=>{
  cb(null, require('./b').default)
},'abc') // the same before chuck name
```
First started is OK！！！！，but i change：

```JS
require.ensure([], (require)=>{
  cb(null, require('./b').default)
},'ccc') // change this
```
have problem: `Cannot read property 'call' of undefined at __webpack_require__.`

Do not change anything，Just started is OK！！！！

**Comment by ktunkiewicz** [comment]
I had the same issue when using dynamic imports, in production mode only.

When you look at the function that executes module:
```javascript
    function __webpack_require__(moduleId) {
        // Check if module is in cache
        if (installedModules[moduleId]) {
            return installedModules[moduleId].exports;
        }
        // Create a new module (and put it into the cache)
        var module = installedModules[moduleId] = {
            i: moduleId,
            l: false,
            exports: {}
        };
        // Execute the module function
        modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
        // Flag the module as loaded
        module.l = true;
        // Return the exports of the module
        return module.exports;
    }
```

In my case the moduleId `373` that I was importing dynamically did exist in `installedModules` (with `l: false`) but did not exist in `modules`. 

When the same code was run without production mode, the *module names were strings* because I use the `NamedModulesPlugin` and this *situation did not happen*.

This gave me a hint that there's some bug related to module naming. Then I tried `HashedModuleIdsPlugin` and it *worked fine*.

So, for me the fix was to use `HashedModuleIdsPlugin` in production and `NamedModulesPlugin` in dev.

**Comment by sergonius** [comment]
Same thing: production mode, dynamic imports – doesn't work.
For me, using `HashedModuleIdsPlugin` doesn't work, sadly.

**Comment by mweststrate** [comment]
I have the same issue, only in production builds. However, the problem disappeared when disabling my ad-blocker (Easy AdBlock)

**Comment by vrozaev** [comment]
I have some problem. I find out that problem in my css loader `ExtractTextPlugin`.

I set `allChunks: true` and this fix my problem.

By some reason separate css chunks are not supported.

PS:
you can debug your problem if you set

```
optimization: {
    namedModules: true,
    namedChunks: true
}
```

In that case you can SEE which module is failed to load.

**Comment by vahoang** [comment]
Tks @vrozaev , I got this problem too using `Webpack 4`, `react-loadable` and `ExtractTextPlugin.`

Found a same case and solved here [react-loadable Chunks loaded but code not executed](https://stackoverflow.com/questions/50786867/react-loadable-chunks-loaded-but-code-not-executed)

Install `babel-plugin-syntax-dynamic-import` and set `allChunks: true` fixed my problem.

**Comment by meglio** [comment]
Were there any updates to the reproduction of this issue since then? I too have the issue appear as soon as I switch to "production" mode (v4.25.1).

I don't have any environment specific rules in my webpack config file. So switching to production mode should be affecting some dependencies or default configuration.

**Comment by jsnfwlr** [comment]
@ooflorent any update on this after having a Webpack4 reproducible example provided?

I have just migrated from Webpack 3 to 4, and have the same problem, two identical webpack configs, and if I change mode from 'development' to 'production' every thing breaks. I have dynamic imports for my vue components, and if I remove them, it goes back to working again.

**Comment by guduf** [comment]
On webpack 4, remove `new webpack.optimize.LimitChunkCountPlugin({maxChunks: 10})` fixed my problem.

**Comment by wmertens** [comment]
I'm having the same issue (crash in __webpack_require) with 4.28.4 in dev mode, on hot reload. It doesn't seem to be related to naming, but somehow to differences between `installedModules` and `modules`.

Trying to `require("./lib/universal/Root.jsx")` in a hot reload accept function:

```
> Object.keys(modules).filter(k=>!/node/.test(k))
 ["0", "./assets/app-icon.png", "./assets/images/bg_texture.jpg", "./assets/images/doves.jpg", "./assets/images/homepage/banners/banner_7.jpg", "./assets/images/maps/r$ardeche.png", "./assets/images/maps/r$boedapest.png", "./assets/images/maps/r$costaBlanca.png", "./assets/images/maps/r$costaBrava.png", "./assets/images/maps/r$costaDeLaLuz.png", "./assets/images/maps/r$costaDelSol.png", "./assets/images/maps/r$coteDazur.png", "./assets/images/maps/r$dordogne.png", "./assets/images/maps/r$hauteSavoieSavoie.png", "./assets/images/maps/r$hautesAlpes.png", "./assets/images/maps/r$lagoDiGarda.png", "./assets/images/maps/r$languedocRoussillon.png", "./assets/images/maps/r$lesPyrenees.png", "./assets/images/maps/r$livorno.png", "./assets/images/maps/r$marrakech.png", "./assets/images/maps/r$mugla.png", "./assets/images/maps/r$normandie.png", "./assets/images/maps/r$provence.png", "./assets/images/maps/r$toscane.png", "./assets/images/maps/r$umbria.png", "./assets/images/maps/r$vendee.png", "./assets/images/maps/r$verbier.png", "./assets/images/maps/undefined maps/map_spanje_costa_azahar.png", "./assets/images/maps/undefined maps/map_spanje_costa_de_almeria.png", "./assets/images/maps/undefined maps/map_spanje_costa_tropical.png", "./assets/images/weekbg.png"]

> Object.keys(installedModules).filter(k=>!/node/.test(k))
 ["0", "./assets/images/bg_texture.jpg", "./assets/app-icon.png", "./assets/images/homepage/banners/banner_7.jpg", "./assets/images/maps/r$provence.png", "./lib/universal/Root.jsx"]
10:11:21.365 
```

so weird :(

**Comment by wmertens** [comment]
I think this may be the same: #7829

**Comment by zoro00000000** [comment]
After npm install and npm install webpack-dev-server@x.x.x ! Solved my problem!

**Comment by tonyanziano** [comment]
Was facing this same issue after we upgraded from `webpack-dev-server@3.2.1` to `webpack-dev-server@3.3.1`. Went back down to `3.2.1` and everything worked again.

**Comment by evilebottnawi** [comment]
@tonyanziano future webpack version can be incompatibility with `3.2.1` due internal bugs, you still should upgrade

**Comment by kelihansen** [comment]
Upgrading from webpack-dev-server@3.3.0 to webpack-dev-server@3.3.1 was also a breaking change for us, apparently because of https://github.com/webpack/webpack-dev-server/commit/b31cbaaf49417eb4adf8949cd87c36ca82653b25. After seeing this error and (way too much) investigating, we seem to have fixed the issue by adding ''webpack-dev-server/client?http://localhost:3100' to our `entry` array.

**Comment by DDroll** [comment]
@evilebottnawi what's the difference, how many bugs in the current version, if the newer version doesn't work at all? 
By the way, rollback to 3.2.1 solved problem for me, thanks, @zoro00000000

**Comment by evilebottnawi** [comment]
Please open issue in dev server repo with reproducible test repo, also we fix many issues in master branch, please try, feel free to report any problem, release was in Monday

**Comment by Komald** [comment]
Commenting `chunkFilename` and downgrading to `webpack-dev-server@3.2.1` worked for me too.
Cheers @tonyanziano and @aaronbeall

**Comment by evilebottnawi** [comment]
Solved in webpack-dev-server@4.3.1

**Comment by vkurlyan** [comment]
evilebottnawi Latest webpack-dev-server version is 3.7.2 now. Do you mean webpack@4.3.1 ?

**Comment by evilebottnawi** [comment]
@vkurlyan yep

**Comment by douglas-treadwell** [comment]
@vkurlyan @evilebottnawi still happening for me in webpack@4.4.0

**Comment by evilebottnawi** [comment]
@douglas-treadwell please create minimum reproducible test repo, problem only with webpack-dev-server? if yes please open issue in webpack-dev-server, thanks!

**Comment by ansbar** [comment]
I got different error messages when trying to use dynamic expressions in import(), like:

```
import(/* webpackChunkName: "conf-" */`./components/formengine/configs/${config}.js`).then(config => { } 
```

Either it couldnt find a chunk or call undefined. For me a quick fix was to change the webpackChunkName to something new and rebuild but the thing that solved it permanentaly was adding contenthash like below.
```
output: {
  filename: '[name].[contenthash].js'
}
```

**Comment by bradicalone** [comment]
Problem was the same as most with webpack-dev-server, tried rolling back from webpack-dev-server@3.8.2  to webpack-dev-server@3.2.1 and still didn't work until I updated webpack from webpack@4.0.0 to most recent webpack@4.41.1

**Comment by ed1son67** [comment]
I got a same problem when I just use the ESM to import a function from a js file.And the problem only show up when I use the devServer(Its fine with bundler file).I try to updated my webpack from v4.0.0 to v4.14.0, nothing change.But when I updated webpack to the most recent version 4.41.1,the bug is gone,So I think this bug already fixed in lastest version.

**Comment by dimaip** [comment]
One more possible reason to get this error: I was using legacy `extract-text-webpack-plugin` instead of `mini-css-extract-plugin`.

**Comment by petrind** [comment]
> Tks @vrozaev , I got this problem too using `Webpack 4`, `react-loadable` and `ExtractTextPlugin.`
> 
> Found a same case and solved here [react-loadable Chunks loaded but code not executed](https://stackoverflow.com/questions/50786867/react-loadable-chunks-loaded-but-code-not-executed)
> 
> Install `babel-plugin-syntax-dynamic-import` and set `allChunks: true` fixed my problem.

This helps me, but only use https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import

**Comment by LipeTuga** [comment]
I got the same problem, and believe or not i solved the problem changing the name of the folder containing the component where i got the problem.

**Comment by wmertens** [comment]
Maybe it's due to caching? If it happens again, try to remove the babel and webpack caches (wherever those are)

**Comment by Shubham819** [comment]
I am facing the same issue  with webpack 4.3.0 and webpack dev server 3.11.0

**Comment by goloveychuk** [comment]
You can also try to set unique `output.jsonpFunction` function name.

**Comment by evilebottnawi** [comment]
Somebody can create reproducible test repo?

**Comment by itmayziii** [comment]
@evilebottnawi 

I can't reproduce this issue when creating my own Webpack configuration. The only time I can get a consistent reproduction is when using Gatsby with loadable components which will give "WebpackError: TypeError: Cannot read property 'call' of undefined." I've been trying to reverse engineer their webpack config to solve this but I've been unsuccessful. 

I created a [minimal repository using Gatsby](https://github.com/itmayziii/gatsby-webpack-call-undefined) to hopefully help you diagnose the problem. It doesn't seem like anyone has been able to provide reproduction of the issue with a minimal project so I believe this minimal Gatsby project is as good as we have for now. I left some details in the README.

**Comment by evilebottnawi** [comment]
In my TODO

**Comment by evilebottnawi** [comment]
Reproduced, WIP

**Comment by evilebottnawi** [comment]
Without `loadable`, it output, so error don't lie, `nothing` to call :smile: :
```
UnhandledPromiseRejectionWarning: Error: Cannot find module '../modules/module-one'
```

Something wrong with resolving, I think better place for it is `Gatsby` repo, there are a lot of additional stuff from `gatsby`

**Comment by danielmariz** [comment]
if you're using webpack 3 and babel 6 install `babel-plugin-syntax-dynamic-import` and set the plugin on babelrc.
if you're using webpack 4+ and babel 7 https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import
if you're using `ExtractTextPlugin` set `allChunks: true` in the pluging configs

That solved the issue for me

**Comment by restuwahyu13** [comment]
follow step by step this solution for fix this problem, working with me using webpack 4

1.STEP ONE 
output: {
  library: '[name]',
  umdNamedDefine: false
}

optimization: {
  concatenateModules: false,
  providedExports: false,
  usedExports: false
}

2. STEP TWO
remove symlink and caheWithContenxt

3. STEP THREE
remove old project name in heroku, after remove old project create new project name

**Comment by zlj002** [comment]
Extract from all additional chunks too (by default it extracts only from the initial chunk(s))
When using CommonsChunkPlugin and there are extracted chunks (from ExtractTextPlugin.extract ) in the commons chunk, allChunks must be set to true

**Comment by evilebottnawi** [comment]
`ExtractTextPlugin` was deprecated, please migrate on `mini-css-extract-plugin`, I want to close this issue, if you faced with the same issue using `webpack@4`/`webpack@5` and `mini-css-extract-plugin` or without the plugin, please open new issue with reproducible test repo, a lot of

**Comment by MDanialShaukat** [comment]
Same issue I have faced and comment of @vrozaev helped me. I have added 
```
optimization: {
    namedModules: true,
    namedChunks: true
}
```
in webpack. After adding I have shown the file name that contains the problematic code.

![image](https://user-images.githubusercontent.com/62928720/100356260-cbb44400-3014-11eb-94cf-05ac84c44485.png)

Thanks @vrozaev

**Comment by Triggsy22** [comment]
I had a similiar issue 'Cannot read property 'call' of undefined at \_\_webpack_require__'.
I was writing a Plugin for Shopware6 and had to import some node modules when this error appears at production compilation. But not at dev compilation.

First i had to change all import to require. Like @hannadrehman allready mentioned 3 years ago.

Additional i had to add the following optimization statement:

```
optimization: {
	splitChunks: {
		cacheGroups: {
			'runtime-vendor': {
				chunks: 'all',
				name: 'vendors-node',
				test: join(__dirname, 'node_modules')
			}
		},
		minSize: 0
	}
}
```

**Comment by alexander-akait** [comment]
Do you use webpack v5? If yes, please create reproducible test repo, maybe we can improve our errors and improve DX
