### ISSUE TITLE
Banner plugin is broken in production mode

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#6630]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

**Configuration:**

```
module.exports = {
  plugins: [
    new webpack.BannerPlugin({
      banner: "foobar",
    }),
  ],
};
```

If compiled in `production` mode, the banner doesn't appear in the output. It does appear in `development` and `none` modes.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above. Attach the plugin to a build to test.

**What is the expected behavior?**

The banner should appear in the build.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.0.1.

**Comment by sokra** [comment]
Did you have any non-standard uglifyjs configuration? i. e. `comments: false`

**Comment by bebraw** [comment]
It's the standard minification configuration provided by production mode. If it strips comments, that would explain the issue.

**Comment by ooflorent** [comment]
I can reproduce the issue. `UglifyJsPlugin` strips the comment.

**Comment by evilebottnawi** [comment]
Should we use `regex` to detect banner and don't touch this

**Comment by ooflorent** [comment]
@evilebottnawi that would be really hard. The banner may be complex. IMO the solution is the use `extractComments.banner` instead of `BannerPlugin`.

**Comment by sokra** [comment]
In my opinion uglify shouldn't remove these comments by default. Removing license comments isn't that good.

**Comment by evilebottnawi** [comment]
@sokra we already have issue https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/222. We can close this issue, but better will be create tests case to avoid problem in future, i don't have time right now for this. Issue in `uglifyjs-webpack-plugin` i will close in near time

**Comment by ooflorent** [comment]
Maybe `uglify-js` was keeping `/*!` and `uglify-es` is not. We could set `comments` to preserve the old behavior.

**Comment by chrisdothtml** [comment]
How do you fix this if you want license banners removed _and_ your own banner, though?

**Comment by ma2ciek** [comment]
Anyway, `webpack.BannerPlugin` should add a banner after the uglification takes place. Consider a case when each source file contains license at the beginning, but you want to have only one license in the bundle. That's impossible right now. I had to change the final banner a little bit and add a regexp for `webpack.BannerPlugin` to preserve only the final license banner and remove other banners with same messages.

**Comment by slavafomin** [comment]
Maybe the option could be introduced, which would control when the banner will be added before or after minification?

**Comment by evilebottnawi** [comment]
Banner plugins doesn't use by default

**Comment by lucianosantana** [comment]
Solution is here : https://github.com/webpack/webpack-cli/issues/312

**Comment by Venipa** [comment]
> Solution is here : [webpack/webpack-cli#312](https://github.com/webpack/webpack-cli/issues/312)

usage of variables is lost in production builds if you use this method, not a "real" fix

**Comment by marcogrcr** [comment]
> > Solution is here : [webpack/webpack-cli#312](https://github.com/webpack/webpack-cli/issues/312)
> 
> usage of variables is lost in production builds if you use this method, not a "real" fix

@Venipa: If by *"usage of variables"* you mean using a `Function` value for the `banner` property, I was able to workaround it with the following:

```js
let inUserScriptHeader = false;

module.exports = {
  plugins: [
    new webpack.BannerPlugin({
      banner: ({ chunk }) => `// ==UserScript==
// @name ${chunk.name}
// ==/UserScript==`,
    }),
  ],
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          output: {
            comments: (_, comment) => {
              if (comment.value === " ==UserScript==") {
                inUserScriptHeader = true;
              } else if (comment.value === " ==/UserScript==") {
                inUserScriptHeader = false;
                return true;
              }

              return inUserScriptHeader;
            }
          }
        }
      })
    ]
  }
};
```

**Comment by PillarsZhang** [comment]
I'm trying to solve the problem at its root.

- In **terser-webpack-plugin**, the stage to tap into 'processAssets' is [PROCESS_ASSETS_STAGE_OPTIMIZE_SIZE](https://github.com/webpack-contrib/terser-webpack-plugin/blob/491b2fd25dd42723ba3368ff15a8aa32f647d8a4/src/index.js#L658).

- In **BannerPlugin**, the stage is [PROCESS_ASSETS_STAGE_ADDITIONS](https://github.com/webpack/webpack/blob/c46ccfb56a6de8b33739c81b665f0d3bcd17ffaf/lib/BannerPlugin.js#L85).

According to the [API Document](https://webpack.docschina.org/api/compilation-hooks/#list-of-asset-processing-stages). The latter will be implemented earlier in the process. That's why the comment is finally removed.

So my solution is to modify **BannerPlugin**, just replace PROCESS_ASSETS_STAGE_ADDITIONS with other stage like PROCESS_ASSETS_STAGE_OPTIMIZE_TRANSFER. The webpack configuration file can remain the same. I have tried 'production' mode with the modified BannerPlugin and it works fine.

I am very glad to have found a package called [*patch-package*](https://github.com/ds300/patch-package), which enables me to modify webpack easily. Here are the patches it generates.
```
diff --git a/node_modules/webpack/lib/BannerPlugin.js b/node_modules/webpack/lib/BannerPlugin.js
index 81b7658..caa26f8 100644
--- a/node_modules/webpack/lib/BannerPlugin.js
+++ b/node_modules/webpack/lib/BannerPlugin.js
@@ -82,7 +82,7 @@ class BannerPlugin {
 			compilation.hooks.processAssets.tap(
 				{
 					name: "BannerPlugin",
-					stage: Compilation.PROCESS_ASSETS_STAGE_ADDITIONS
+					stage: Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_TRANSFER
 				},
 				() => {
 					for (const chunk of compilation.chunks) {

```

**Comment by alexander-akait** [comment]
We need the new options for banner plugin, `afterMinize: true | false` and use other hook, feel free to send a PR, we have the same request for CSS too https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/64

**Comment by matzeeable** [comment]
Solved it this way by excluding `@preamble` from being extracted:

```js
const config = {
    optimization: {
        minimizer: [
            // https://git.io/Jo5g3
            new TerserWebpackPlugin({
                terserOptions: {
                    compress: {
                        passes: 2
                    }
                },
                // https://git.io/Jo5Vf
                extractComments: (astNode, comment) => {
                    return (
                        (comment.type === "comment2" || comment.type === "comment1") &&
                        /@preserve|@lic|@cc_on|^\**!/i.test(comment.value) &&
                        comment.value.indexOf("@preamble") === -1
                    );
                }
            }),
            "..."
        ]
    },
    plugins: [
        new BannerPlugin({
            banner: "My banner\n\n@preamble"
        })
    ]
};
```

**Comment by matzeeable** [comment]
@alexander-akait If I use the code snippet from above, the debugger within the source map no longer works as expected:

![image](https://i.imgur.com/iwjv8bv.gif)

Do you have an idea what causes this? When I disable the `BannerPlugin` the debugger works as expected.

**Comment by alexander-akait** [comment]
Source maps generated after banner plugin https://github.com/webpack/webpack/blob/d106f00db56e5b9a1c2ed43266f1837f846f4ce8/lib/Compilation.js#L5105

**Comment by matzeeable** [comment]
That is strange. If I manually adjust the bundle asset and remove the first 4 lines (the banner itself), then the debugger works again. Something must be going wrong here on the part of the source map generation. Can you reproduce the problem?

**Comment by alexander-akait** [comment]
No... Can you provide example?

**Comment by matzeeable** [comment]
Unfortunately, I cannot create a reproduction as with a plain webpack installation, it works as expected: https://stackblitz.com/edit/github-uymwfx - it must be something on my end...

**Comment by alexander-akait** [comment]
Try to update deps locally (remove `package-lock.json`and run `npm install` again), but bug on `terser` side with source map generation... but if it works fine with fresh install maybe already fixed

**Comment by alexboots** [comment]
I followed along with [matzeeable](https://github.com/matzeeable)'s suggestion and it worked for my use case! But wondering if this could remain open until this is properly resolved with the addition of `afterMinize: true | false` :)

**Comment by magicdawn** [comment]
why closed, don't see a simple solution

**Comment by ma2ciek** [comment]
> `BannerPlugin` doesn't do magic, just inject comments/code in code...

Shouldn't BannerPlugin be designed to just add banners and nothing else? Inserting code via BannerPlugin sounds like a hack for me and the whole discussion confirms that the current behavior - adding the banner before the minification - is not good for adding banners.

**Comment by alioshr** [comment]
I still happens with we in using webpack v5. Furthermore, @matzeeable solution did not preserve the comment injected by BannerPlugin for me. It just kept the comments on the licence files, but not on the .js files. I uso craco, by the way =).

**Comment by 0Chan-smc** [comment]
I don't understand why this issue has been closed. This issue still exists in webpack v5.

**Comment by alexander-akait** [comment]
Please create reproducible test repo, thank you

**Comment by pebanfield** [comment]
I was struggling with this issue. Then magically the following configuration is both preserving the banner and stripping the comments. 

```
optimization: {
    usedExports: true,
    minimize: true,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: {
            passes: 2,
          },
        },
        extractComments: false,
      }),
    ],
  },
```
My banner plugin usage itself is totally basic - 

`new webpack.BannerPlugin(JSON.stringify(buildInfo)),`

I am using webpack 5. I wish I understood how this configuration works. `passes: 2` perhaps?

**Comment by andrx** [comment]
I used this instead of BannerPlugin
```
    optimization: {
        usedExports: true,
        minimize: true,
        minimizer: [
            new TerserPlugin({
                terserOptions: {
                    compress: {
                        passes: 2,
                    },
                },
                extractComments: {
                    banner: `My Banner\n`
                }
            }),
        ],
    }
```
