### ISSUE TITLE
hash might collide with unidentical file contents when webpack config changes

### ISSUE THREAD

**Issue by villesau** [webpack/webpack#9360]
# Bug report

**What is the current behavior?**

If certain configs are changed, webpack produces different file output, but the calculated hash remaisn the same. This is the case at least with different source map configs: `hidden-source-map` and `source-map` devtools: `source-map` produces line `/*# sourceMappingURL=1-ee230307f9c3ff792b7c.css.map*/` in the end of file which means that the hash should already be there at that point.

This is problematic for CDN since changing webpack config might not propagate to CDN and files in S3 and CDN differs. It's hard to debug why is that. 

This also makes it impossible to validate that file contents & hash matches what we already have in production.

**If the current behavior is a bug, please provide the steps to reproduce.**

Have very basic webpack config. Produce the build with hashes using both types of source maps -> hash remains the same but contents are different.

hash should change when devtool or other settings that change the output changes.

**Potential solution**

Take relevant parts of webpack config into account when calculating the hash. In this case devtool could be part of the hash calculation, as well as e.g different compression types and other relevant configs. I'm not that familiar with Webpack internals, but a naive way to achieve this would be to append relevant configs in the end of files they relate to and then calculate hash from that. If we know that some of the devtools produces identical result, it could be taken into account by mapping the devtools in a way that the identical results does not change when devtool or other similar settings changes.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: v10.15.0
Operating System: macOS
Additional tools: -

E: There is a related feature request: https://github.com/webpack/webpack/issues/7787

**Comment by villesau** [comment]
Still valid.

**Comment by villesau** [comment]
This is still relevant.

**Comment by evilebottnawi** [comment]
@villesau can you test latest webpack@5?

**Comment by sokra** [comment]
Should be fixed in webpack with the realContentHash, which calculates a hash of the content.

**Comment by evilebottnawi** [comment]
Yes, I just want to make sure we don't get edge case here.

**Comment by villesau** [comment]
@evilebottnawi @sokra Couldn't reproduce anymore with realContentHash=true. Great job! The fix saves a ton of time from devs who would otherwise hit into this problem eventually! :D

I can also confirm that with realContentHash=false, the problem still exist, but I guess that's intentional.

Thank you!

**Comment by evilebottnawi** [comment]
@villesau maybe you can create minimum reproducible test repo, because ideally it should work without `realContentHash` :smile:

**Comment by sokra** [comment]
The SourceMapDevToolPlugin could fix that by adding the comment template to the chunk hash via the chunkHash hook.
