### ISSUE TITLE
Error when using cheap-module-source-map

### ISSUE THREAD

**Issue by robrichard** [webpack/webpack#954]
```
TypeError: Cannot read property '0' of undefined
    at processMapping (/jenkins/jenkinsjobs/Admin-v2 Deploy (QA)/workspace/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/fromStringWithSourceMap.js:51:54)
    at /jenkins/jenkinsjobs/Admin-v2 Deploy (QA)/workspace/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/fromStringWithSourceMap.js:28:16
    at Array.forEach (native)
    at fromStringWithSourceMap (/jenkins/jenkinsjobs/Admin-v2 Deploy (QA)/workspace/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/fromStringWithSourceMap.js:20:11)
    at SourceMapSource.listMap (/jenkins/jenkinsjobs/Admin-v2 Deploy (QA)/workspace/node_modules/webpack/node_modules/webpack-core/lib/SourceMapSource.js:47:9)
    at SourceMapSource.proto.sourceAndMap (/jenkins/jenkinsjobs/Admin-v2 Deploy (QA)/workspace/node_modules/webpack/node_modules/webpack-core/lib/SourceAndMapMixin.js:19:16)
    at Tapable.<anonymous> (/jenkins/jenkinsjobs/Admin-v2 Deploy (QA)/workspace/node_modules/webpack/lib/SourceMapDevToolPlugin.js:56:32)
    at Array.map (native)
    at Tapable.<anonymous> (/jenkins/jenkinsjobs/Admin-v2 Deploy (QA)/workspace/node_modules/webpack/lib/SourceMapDevToolPlugin.js:44:84)
    at Array.forEach (native)
```

**Comment by robrichard** [comment]
I got the same error when trying this on two different projects (but they do share a lot of code). How should I debug this?

**Comment by robrichard** [comment]
@sokra I just installed webpack@1.8.1 and got a different error with ```cheap-module-source-map``` enabled:

```
TypeError: Not a valid base 64 digit: ,
    at Object.base64_decode [as decode] (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/base64-vlq.js:68:9)
    at Object.base64VLQ_decode [as decode] (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/base64-vlq.js:160:20)
    at processMapping (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/fromStringWithSourceMap.js:46:13)
    at /Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/fromStringWithSourceMap.js:28:16
    at Array.forEach (native)
    at fromStringWithSourceMap (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/webpack-core/node_modules/source-list-map/lib/fromStringWithSourceMap.js:20:11)
    at SourceMapSource.listMap (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/webpack-core/lib/SourceMapSource.js:47:9)
    at SourceMapSource.proto.sourceAndMap (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/webpack-core/lib/SourceAndMapMixin.js:19:16)
    at Tapable.<anonymous> (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/lib/SourceMapDevToolPlugin.js:56:32)
    at Array.map (native)
```

**Comment by sokra** [comment]
@robrichard I take a look

**Comment by sokra** [comment]
I hope this is fixed by webpack/source-list-map@3f7fb100d692ec29cd151a304308044dceb6e301

**Comment by robrichard** [comment]
I updated source-list-map and got a new error:
```
TypeError: Cannot call method 'readableIdentifier' of undefined
    at Object.createFilename (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/lib/ModuleFilenameHelpers.js:57:32)
    at /Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/lib/SourceMapDevToolPlugin.js:78:36
    at Array.map (native)
    at Tapable.<anonymous> (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/lib/SourceMapDevToolPlugin.js:77:36)
    at Array.map (native)
    at Tapable.<anonymous> (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/lib/SourceMapDevToolPlugin.js:72:30)
    at Array.forEach (native)
    at Tapable.<anonymous> (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:11)
    at Tapable.applyPlugins (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Tapable.<anonymous> (/Users/rob/projects/1stdibs-admin-v2/node_modules/webpack/lib/Compilation.js:543:10)
```

**Comment by sokra** [comment]
The root cause seem to be a weird SourceMap. Which loader does generate such SourceMaps? They seem to have no `sources`.

**Comment by robrichard** [comment]
I'm using babel for es6 & jsx and the built in uglify plugin

**Comment by s-panferov** [comment]
@sokra, this still appears on my codebase with `webpack@1.12.1`:

```
/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/ModuleFilenameHelpers.js:106
			" ** " + module.readableIdentifier(requestShortener),
			               ^
TypeError: Cannot read property 'readableIdentifier' of undefined
    at Object.createFooter (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/ModuleFilenameHelpers.js:106:19)
    at /Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/SourceMapDevToolPlugin.js:117:57
    at Array.map (native)
    at Compilation.<anonymous> (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/SourceMapDevToolPlugin.js:116:58)
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/SourceMapDevToolPlugin.js:106:10)
    at Compilation.applyPlugins (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Compilation.<anonymous> (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/Compilation.js:570:10)
    at Compilation.next (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/ProgressPlugin.js:65:5)
    at Compilation.applyPluginsAsync (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.next (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/panferov-s/Workspace/alfa-listing/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Compilation.applyPluginsAsync (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/panferov-s/Workspace/alfa-listing/node_modules/webpack/lib/Compilation.js:562:8)
```

**Comment by s-panferov** [comment]
@sokra I'm trying to debug the error. I've just found out that I have an `undefined` item within `sourceMap.sourcesContent` list.

**Comment by s-panferov** [comment]
I've tried to insert console.log here https://github.com/webpack/webpack/blob/master/lib/SourceMapDevToolPlugin.js#L117

```
content == undefined && console.log(moduleFilenames[i], modules[i]);
```

and I get 

```
> webpack:/// undefined
```

**Comment by s-panferov** [comment]
@sokra I think that [this](https://github.com/webpack/webpack/blob/master/lib/ModuleFilenameHelpers.js#L50) check is also must be present here: 

https://github.com/webpack/webpack/blob/master/lib/ModuleFilenameHelpers.js#L96

**Comment by use-strict** [comment]
@sokra , this is still an issue with the lastest webpack. Can you reopen it?

**Comment by hgoebl** [comment]
I'm getting this error (Cannot read property 'readableIdentifier' of undefined) as well when using `devtool: "eval-cheap-module-source-map"`.
My config: webpack 1.12.2, using `ts-loader`

**Comment by andrew-w-ross** [comment]
+1 this is still a problem

**Comment by thomasmodeneis** [comment]
I'm also having this error on 
```$ node --version 
v5.9.1
```

And webpack version:
```
"webpack": "1.9.11",
"webpack-dev-server": "1.9.0"
--
[1] /opt/test/node_modules/webpack/lib/ModuleFilenameHelpers.js:94
[1] 			" ** " + module.readableIdentifier(requestShortener),
[1] 			               ^
[1] 
[1] TypeError: Cannot read property 'readableIdentifier' of undefined
[1]     at Object.createFooter (/opt/test/node_modules/webpack/lib/ModuleFilenameHelpers.js:94:19)
[1]     at Tapable.<anonymous> (/opt/test/node_modules/webpack/lib/EvalSourceMapDevToolModuleTemplatePlugin.js:55:55)
[1]     at Array.map (native)
[1]     at Tapable.<anonymous> (/opt/test/node_modules/webpack/lib/EvalSourceMapDevToolModuleTemplatePlugin.js:54:56)
[1]     at Tapable.applyPlugins [as applyPluginsWaterfall] (/opt/test/node_modules/tapable/lib/Tapable.js:37:47)
[1]     at Tapable.ModuleTemplate.render (/opt/test/node_modules/webpack/lib/ModuleTemplate.js:15:22)
[1]     at Tapable.Template.renderChunkModules (/opt/test/node_modules/webpack/lib/Template.js:80:31)
[1]     at Tapable.ChunkTemplate.render (/opt/test/node_modules/webpack/lib/ChunkTemplate.js:16:21)
[1]     at Tapable.createChunkAssets (/opt/test/node_modules/webpack/lib/Compilation.js:820:33)
[1]     at Tapable.<anonymous> (/opt/test/node_modules/webpack/lib/Compilation.js:546:8)
[1] node webpack.server.js exited with code 1
--> Sending SIGTERM to other processes..
[2] gulp css:watch exited with code null
[0] nodemon --harmony_array_includes app/server exited with code 0
```
