### ISSUE TITLE
Error : ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory'...

### ISSUE THREAD

**Issue by felixbillon** [webpack/webpack#981]
Hi everybody.

I'm simply trying to use webpack but i can't solve this error.

This is my webpack.config.js : 

```
module.exports = {
  entry: './index.js',
  output: {
    filename: 'bundle.js'
  }
};
```

I try many thing but nothing change... I'm using last version of webpack 1.8.4.

I got this error : 

```
Running "webpack:build-dev" (webpack) task
Version: webpack 1.8.4

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./index.js in D:\myApp\src
Warning: Task "webpack:build-dev" failed. Use --force to continue.
```

index.js file is in src folder...

Anybody got an idea ?

**Comment by felixbillon** [comment]
Invisible char issue, not evaluate by npm but cause problem for webpack. Encoding matter.

**Comment by yccteam** [comment]
I have a similiar issue. Could you please add some more info on the solution?

**Comment by jgebhardt** [comment]
Try running `webpack --display-error-details`. The error may not be related to file resolution.

**Comment by epeli** [comment]
Had this error today. I'm commenting here because this is the first hit in Google with the error message.

There was nothing wrong with my `webpack.config.js` but there was a syntax error my `package.json` which caused this. Better error message would be cool.

This error has been seen here too https://github.com/webpack/karma-webpack/issues/33

**Comment by lucygeneric** [comment]
wow thanks @jgebhardt  --display-error-details saved my bacon

**Comment by Hancoson** [comment]
I had the same error, help me

**Comment by That-David-Guy** [comment]
Thanks @epeli! Spent a while looking through my gulpfile.js when I had a comma on the last item in my devDependencies in package.json

Terrible error message

**Comment by giyyapan** [comment]
@epeli @That-David-Guy Same error, same fix! Thanks. lol

**Comment by maharshioza** [comment]
@jgebhardt Thanks. -display-error-details helped to resolve error.

**Comment by mlent** [comment]
For those arriving by search: I had this issue because I was using `html-loader` in my webpack config, *and* had `require`s prefixed with `html!`. This caused my options in the config to get ignored for every file.

**Comment by flyher** [comment]
@jgebhardt 
thank you very much~~~

**Comment by mauriciosoares** [comment]
@epeli thanks man! indeed the error were in my `package.json`

**Comment by qintengfei** [comment]
resolve by this : http://webpack.github.io/docs/configuration.html#resolve-extensions

**Comment by let4be** [comment]
Why does _not_ webpack print such obvious errors as unability to parse package.json?
my package.json was corrupted and webpack gave me mysterious errors about unability to resolve absolute path...

**Comment by tikitariki** [comment]
A lot of people have stated that they had a broken package.json. Well, how does that happen? What qualifies as broken? I never modify it. All I did was add webpack as a dependency, installed, and ran it. My webpack.config.js is super simple and straight from a CSS-Tricks tutorial that's not even two weeks old.

What resolved my issue? Well, I wanted to test out webpack, but I guess my JS structure (just a bunch of files concat'd via a build tool) was not immediately compatible. I just pointed my entry at a new blank file that didn't have these conflicting files and everything was alright. Hope this helps others arriving here.

**Comment by KCreate** [comment]
`npm install file-loader` fixed the issue for me.

**Comment by kidbai** [comment]
I have the same problem beacause of my package.json got a syntax error :)

**Comment by Mark-Brightcloud** [comment]
0. Restart Terminal(Mac) or whatever shell in your environment.

1. Add FIXFIX in package.json like this:
`"scripts": {
    "FIXFIX": "webpack --progress --profile --colors --display-error-details --display-cached",
  },`

2. Run this: (Yes, with sudo!)
`sudo node run FIXFIX`

3. Now run with your normal build see if it fixed.

**Comment by atorralb** [comment]
I think it has to do with the new webpack version where you have to specify "resolve".
My project didn't work until I added it this line:
` resolve: {
        modulesDirectories: ['node_modules', 'src'],
        extension: ['', '.js', '.scss']
    },`

**Comment by Head** [comment]
wtf. Had this error because I had one line commented out. with /* ... */. Is webpack kidding me?

**Comment by janejanejane** [comment]
I had the error because this: `extenstions: [ '', '.js', '.jsx' ]`. :dizzy_face:

**Comment by sgshawnblanchard** [comment]
thanks @atorralb .  I addded `"src"` to the `modulesDirectories` array and the issue was resolved.

**Comment by xukuanzhuo** [comment]
thx @jgebhardt  helped to resolve error.

**Comment by RamonSchmitt** [comment]
> details

jhgfsdlvvn=r`
p[
ytop[[ug=op[]
op[[v\;lycv;rlds
asdcdkcx/[ss\ vc
nnss
hgf,\ f\

**Comment by Simmer-Jun** [comment]
Thx @atorralb! My error has been fixed!

**Comment by sparachi** [comment]
ERROR in multi polyfills Module not found: Error: Cannot resolve module 'ts' blah blah....

and similarly

ERROR in multi polyfills Module not found: Error: Cannot resolve module 'html'

to solve this basically I had to do a dev install of "npm install ts-loader --save --only=dev" &&  "npm install html-loader --save --only=dev"


there were bunch of other loaders which were missing, so installed them all.

**Comment by abrahamhall84** [comment]
@janejanejane how did you resolve the `extenstions: [ '', '.js', '.jsx' ]`? did you have to take off '.jsx'?

**Comment by Andorbal** [comment]
In my case, the problem was:
`entry: path.resolve(__dirname, '/src/index.js'),`
instead of:
`entry: path.resolve(__dirname, 'src/index.js'),`

Notice the slash in front of src in the original version.

**Comment by larry-dalmeida** [comment]
This was my config:

`context: __dirname + "/app",

  entry: "./app.js",

  output: {
    path: __dirname + "/dist",
    filename: "app.bundle.js"
  },`

But I am using Windows and the path was incorrect because Windows uses a backslash.

Fixed with this:

`context: __dirname + "\\app",

  entry: "./app.js",

  output: {
    path: __dirname + "\\dist",
    filename: "app.bundle.js"
  },`

Wow. What a relief!

**Comment by wayofthefuture** [comment]
Man this one really made me regret being a computer programmer. I was able to resolve the issue by changing:

```javascript
        extensions: ['.js', '.jsx']
```
To this:
```javascript
        extensions: ['', '.js', '.jsx']
```

**Comment by isaacalves** [comment]
thanks @atorralb, that was it

**Comment by Endlessline** [comment]
I was able to fix the error by removing a line I had commented out with '//'

**Comment by sqlsolver** [comment]
@Endlessline - thanks, that fixed it for me also. I wonder if this closes the door to documentation generators that scrape comments?

**Comment by snowy-dong** [comment]
@epeli @jgebhardt --thanks,same error ,a good way to solve the problems.

**Comment by wtfil** [comment]
fixed by changing
```js
context: __dirname + '/app'
```

to

```js
context: path.join(__dirname, '/app')
```

**Comment by kyasbal-1994** [comment]
I also could solve this problem with the solution @wayofthefuture pointed out. I think this must be bug obviously.

**Comment by dragonahao** [comment]
webpack 1.13 does not compact with webpack@beta2 , use beta2 is OK

**Comment by shireefkhatab** [comment]
my problem was 
module.exports = {
	entry: 'src/scripts/main.js',
	output: {
		path: __dirname + '/build',
		bublicPath: '/build/',
		filename: 'bundle.js'
	}
} and when added  ./ before src it worked  so:

module.exports = {
	entry: './src/scripts/main.js',
	output: {
		path: __dirname + '/build',
		bublicPath: '/build/',
		filename: 'bundle.js'
	}
}

**Comment by slawo** [comment]
adding `""` to the `extensions` array helped I am really lost as to why this error message is so obscure.

**Comment by codingplayboy** [comment]
I have the error, today.
You can check resolve property in you webpack.config.js file:
such as:
```
resolve: {
        root: [
            path.resolve('./app'),
            path.resolve('./node_modules')
        ]
    }
````
then, your entry file path is resolve to: ```app/index.js```, or ```node_modules/index.js```, you need check this file.

**Comment by azqazs** [comment]
**Same issue:**
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'config' in '/home/g/mean-todo-app/src'
 @ ./src/index.js 7:14-31
 @ multi main

**with webpack --display error-details**
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'config' in '/home/g/mean-todo-app/src'
resolve 'config' in '/home/g/mean-todo-app/src'
  Parsed request is a module
  using description file: /home/g/mean-todo-app/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/g/mean-todo-app/package.json (relative path: ./src)
    resolve as module
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /home/g/mean-todo-app/src/node_modules doesn't exist or is not a directory
      looking for modules in /home/g/mean-todo-app/node_modules
        using description file: /home/g/mean-todo-app/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/g/mean-todo-app/package.json (relative path: ./node_modules)
          using description file: /home/g/mean-todo-app/package.json (relative path: ./node_modules/config)
            as directory
              /home/g/mean-todo-app/node_modules/config doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/g/mean-todo-app/node_modules/config doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/g/mean-todo-app/node_modules/config.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/g/mean-todo-app/node_modules/config.json doesn't exist
      looking for modules in /home/g/node_modules
        using description file: /home/g/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/g/package.json (relative path: ./node_modules)
          using description file: /home/g/package.json (relative path: ./node_modules/config)
            as directory
              /home/g/node_modules/config doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/g/node_modules/config doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/g/node_modules/config.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/g/node_modules/config.json doesn't exist
[/home/node_modules]
[/node_modules]
[/home/g/mean-todo-app/src/node_modules]
[/home/g/mean-todo-app/node_modules/config]
[/home/g/mean-todo-app/node_modules/config]
[/home/g/mean-todo-app/node_modules/config.js]
[/home/g/mean-todo-app/node_modules/config.json]
[/home/g/node_modules/config]
[/home/g/node_modules/config]
[/home/g/node_modules/config.js]
[/home/g/node_modules/config.json]
 @ ./src/index.js 7:14-31
 @ multi main

**Comment by azqazs** [comment]
**whats going wrong?? this is the webpack file:**

 webpack = require('webpack');
var path = require('path');

module.exports = {
	devtool: 'inline-source-map',
	entry: [
		'webpack-dev-server/client?http://127.0.0.1:8080/',
		'webpack/hot/only-dev-server',
		'./src'
	],
	output: {
		path: path.join(__dirname, 'public'),
		filename: 'bundle.js'
	},
	resolve: {
		modulesDirectories: ['node_modules', 'src'],
		extension: ['', '.js'] 
	},
	module: {
		loaders: [
			   		{
						test: /\.js$/,
						exclude: /node_modules/,
						loader: 'babel',
						query: {
							presets: ['es2015']
		     			}
					},
					{
						test: /\.html$/,
						loader: 'raw' 
					}
		   		]  
			},

	plugins: [
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoErrorsPlugin()
	],
	devServer: {
		hot: true,
		proxy: {
			'*': 'http://localhost:3000'
		}
	}
};

**Comment by philipvella** [comment]
Problem here was **Case Sensitivity**.

from `import App from './app';` to
this  `import App from './App';`

Notice case sensitivity, since my file was **App.js**

**Comment by hanagejet** [comment]
I have the some issue: https://github.com/webpack/webpack/issues/981#issuecomment-276935191

app.js
```js
import store from './store';
```

webpack.config.js
```js
var path = require('path');
var fs = require('fs');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var webpack = require('webpack');

module.exports = {
  context: path.join(__dirname, './'),

  entry: {
    bundle: './app/app.js',
  },

  output: {
    path: path.resolve(__dirname, 'public/assets'),
    publicPath: '/',
    filename: '[name].js',
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          'babel-loader',
        ],
      },
      {
        test: /\.html$/,
        use: [
          'html-loader',
        ],
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          cssModules: {
            localIdentName: '[path][name]---[local]---[hash:base64:5]',
            camelCase: true
          },
        },
      },
    ],
  },

  resolve: {
    modules: [
      process.env.NODE_PATH || 'node_modules',
    ],
  },

  devtool: 'inline-source-map',

  watchOptions: {
    poll: true,
  },

  devServer: {
    contentBase: path.resolve(__dirname, 'public'),
    publicPath: '/',
    port: 7000,
    hot: true,
    inline: true,
    host: '0.0.0.0',
    historyApiFallback: true,
    // https: true,
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      template: './app/index.html',
      filename: 'index.html',
    }),
  ],
};
```

**Comment by hanagejet** [comment]
https://github.com/webpack/webpack/issues/981#issuecomment-279327103
I use vuex. Maybe will be resolved: https://github.com/vuejs-templates/webpack/issues/513

**Comment by zbagley** [comment]
I'd like to also add that this issue will occur when renaming files while npm is running for some IDE's (some sort of cache issue). Fixed by closing all access points to file (IDE and npm) and re-renaming.

**Comment by fritx** [comment]
I occasionally used  edit package.json, and it prepended a `U+FEFF`, then the webpack started to complain about `Error: Entry module not found`.

```diff
-
+<U+FEFF>{
-  "version": "3.4.5b",
+  "version": "3.4.5c",
}
```

It was this issue told me it was related to things like "package.json" and "char issue" and made my day, thanks a lot ;)

**Comment by kingjerod** [comment]
I'm having this same issue. Nothing wrong with my package.json, checked it with linters and also for any file encoding issues / strange characters. Running `webpack --display-error-details` just shows that it can't find the entry files for whatever reason. Also tried switching from relative directory to using path.resolve to give it an absolute directory, still no luck. 

```
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./js/app.js in /home/vagrant/project1
resolve directory
  /home/vagrant/project1/js/app.js/package.json doesn't exist (directory description file)
  /home/vagrant/project1/js/app.js is not a directory (directory default file)
resolve file
  /home/vagrant/project1/js/app.js.json doesn't exist
  /home/vagrant/project1/js/app.js.js doesn't exist
```

webpack.config.js:
```
const path = require('path');
const webpack = require('webpack');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ManifestPlugin = require('webpack-manifest-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: {
    'js'    : './js/app.js',
    'react' : './views/react/index.jsx',
    'css'   : './css/app.scss'
  },
  output: {
    filename: '[name]-[hash].js',
    path: path.resolve(__dirname, 'public/dist')
  },
  module: {
    noParse: /jquery|lodash/,
    rules: [
      {test: /\.(js|jsx)$/, use: 'babel-loader', query: {presets: ['es2015', 'react']}},
      {
        test: /\.(scss|css)$/,
        use: ExtractTextPlugin.extract({
          use: [{loader: "css-loader"}, {loader: "sass-loader"}]
        })
      }
    ]
  },
  plugins: [
    new CleanWebpackPlugin(['public/dist']),
    new webpack.SourceMapDevToolPlugin(),
    new ExtractTextPlugin("css-[hash].css"),
    new ManifestPlugin({fileName: 'rev-manifest.json'})
  ],
  watch: process.env.NODE_ENV != 'production',
  watchOptions: {
    poll: 50,
    ignored: /node_modules/
  },
  devtool: 'cheap-eval-source-map',
  resolve: {
    modules: [
      process.env.NODE_PATH || 'node_modules',
    ]
  }
};
```

**Comment by Groot90** [comment]
Had this problem today.  It also pointed  me to package,json, altough package.json was 100% ok. Problem was in web.config.js.

Cause:
phpStorm IDE has changed the path to my entry script in web.config.js during an auto-refactoring after a file rename operation ( because the file being renamed had been named index.js, same as my entry script).

Solution:
Made sure that path to entry script in web.config.js is valid.

Hope it helps somebody :)

**Comment by kingjerod** [comment]
I was able to fix my problem. The issue was with this line:
`{test: /\.(js|jsx)$/, use: 'babel-loader', query: {presets: ['es2015', 'react']}},`

Instead of `use: 'babel-loader'` it needs to be `loader: 'babel-loader'`. Why this causes webpack to throw an error about not finding the entry point file, I do not know. Basically had to remove chunks of my config until it worked.

**Comment by shachar-i** [comment]
This might be case-sensitivity issues.
For me this happened with a build that worked ok locally on windows and OSX.
It failed on a Linux server because of a certain file we imported with wrong case (we had `import path/fileName` somewhere when the file was named` FileName.js` - note the difference in case).

In Windows, webpack would warn about this but build would succeed. In Linux, it just failed to resolve the path.

**Comment by pachumon** [comment]
webpack --display-error-details.  this saved my day the same is applicable to webpack --display-error-details. as well

**Comment by chinmoyDebnath** [comment]
I reinstalled webpack-dev-server to make it work.

**Comment by njt1982** [comment]
For me, adding `target: 'node'` to the webpack config fixed it. (via https://github.com/josephsavona/valuable/issues/9#issuecomment-65000999).

NO idea why. That isn't in the dev version and I only get the error in dist mode...

**Comment by Dianna** [comment]
@Mark-Brightcloud thanks! That helped me find where the path was breaking.

**Comment by gtabmx** [comment]
I've been on this issue for 3 hours and double-checked everything in this thread. Still no fix, despite everything working perfectly 3 days ago...

ERROR in multi (webpack)-dev-server/client?https://x.x.x.x:8080 ./src/app dev
Module not found: Error: Can't resolve 'dev' in '/Users/thisUser/thisApp'

**Comment by shireefkhatab** [comment]
Remove the " .  " From url
Sent from my iPhone

On 24 Apr 2017, at 04:49, gtabmx <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been on this issue for 3 hours and double-checked everything in this thread. Still no fix, despite everything working perfectly 3 days ago...

ERROR in multi (webpack)-dev-server/client?https://x.x.x.x:8080 ./src/app dev
Module not found: Error: Can't resolve 'dev' in '/Users/thisUser/thisApp'

**Comment by gtabmx** [comment]
Turned out to be the IP address I set (what I was using in place of x.x.x.x) was not my actual IP, since I was working from home...

**Comment by sangramkb** [comment]
![image](https://cloud.githubusercontent.com/assets/28225588/25565670/21727ca4-2de9-11e7-870a-db36125cf359.png)

I am new to react and webpack.
can someone help me out in resolving the above issue ?

**Comment by AndersenTobias** [comment]
This fixed it for me:
http://stackoverflow.com/questions/43107233/configuration-resolve-has-an-unknown-property-root

**Comment by dyarbrough93** [comment]
My error came from webpack looking into the `node_modules` directory for my imported module, instead of locally. So changing
```
import { foo } from 'test'
```
to
```
import { foo } from './test'
```
fixed the error.

Kind of disappointing that one error message has so many possible causes.

**Comment by codejockie** [comment]
`Hash: 2a82a67f90f9aa05ab4a
Version: webpack 1.12.13
Time: 3538ms
    + 1 hidden modules

ERROR in ./app/app.jsx
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:36
    at C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:396:22
    at Array.map (native)
    at OptionManager.resolvePresets (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\op
tions\option-manager.js:385:20)
    at OptionManager.mergePresets (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\opti
ons\option-manager.js:369:10)
    at OptionManager.mergeOptions (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\opti
ons\option-manager.js:328:14)
    at C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:370:14
    at C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:390:24
    at Array.map (native)
    at OptionManager.resolvePresets (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\op
tions\option-manager.js:385:20)
    at OptionManager.mergePresets (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\opti
ons\option-manager.js:369:10)
    at OptionManager.mergeOptions (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\opti
ons\option-manager.js:328:14)
    at OptionManager.init (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\options\opti
on-manager.js:481:10)
    at File.initOptions (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\index.js:211:7
5)
    at new File (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\file\index.js:129:22)
    at Pipeline.transform (C:\dev\comreact\reactboilerplate\node_modules\babel-core\lib\transformation\pipeline.js:48:16
)
    at transpile (C:\dev\comreact\reactboilerplate\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (C:\dev\comreact\reactboilerplate\node_modules\babel-loader\index.js:88:12)`

**Comment by teovoinea** [comment]
The fix for me was adding "" to my resolve extensions
`  resolve: {
    extensions: ["", ".ts", ".tsx", ".js", ".json"],
  }
`

**Comment by techraiders** [comment]
Sorry. I come from angular background, new to react.
Where to add resolve: { extensions: ["", ".ts", ".tsx", ".js", ".json"], }

**Comment by teovoinea** [comment]
@techraiders you would add it to your `webpack.config.js` file

**Comment by techraiders** [comment]
@teovoinea 

Kindly take a look at my webpack.conf.js below and let me know what's wrong?

`var path = require("path");

var DIST_DIR = path.resolve(__dirname, "dist");
var SRC_DIR = path.resolve(__dirname, "src");

var config = {
  entry: SRC_DIR + "/app/index.js",
  output: {
    path: DIST_DIR + "/app",
    filename: "bundle.js",
    publicPath: "/app/"
  },
  module: {
    loaders: [{
      test: /\.js?/,
      include: SRC_DIR,
      loader: "babel-loader",
      query: {
        presets: ["react", "es2015", "stage-2"]
      }
    }]
  },
  extensions: ["", ".ts", ".tsx", ".js", ".json"]
};

module.exports = config;
`

**Comment by martivel** [comment]
I had the same issue. Since later versions of NPM there is a package-lock.json. I resolved this issue by removing trailing comma after an object & deleting the package-lock.json & node_modules. After these steps i ran npm install and it worked.

**Comment by teovoinea** [comment]
@techraiders A snippet from my webpack.config.js
```

const config = {
    //...
    resolve: {
        extensions: ["", '.ts', '.tsx', '.js', '.json'],
    },
    //...
};
module.exports = config;

```

**Comment by MehranJanfeshan** [comment]
I have got this error when I was trying to use `url-loader` and `image-webpack-loader` and I fixed it by installing `file-loader`

`yarn add file-loader -d`

**Comment by martijnn** [comment]
I encountered this error when trying to deploy my application on a linux machine while I developed it on a windows one.
My webpack config file is resolving extensions like ['.js', '.vue', '.json']. By accident I had some files which had the extension .Vue instead of .vue. The .Vue-ones don't get resolved properly.
So like @philipvella already said, inspect your source for **Case Sensitivity**.

**Comment by amaroks** [comment]
In my case I had in my configuration file the following
`	entry: 'entry.js',
`
Changing that to the following:
`	entry: './entry.js',
`
Seems to solve it!

**Comment by brandonferrer** [comment]
I had the same ERROR in Entry module not found message, and my resolution was that I was in some random directory. I cd to the root of my project, and webpack ran with no issues.

**Comment by TheLarkInn** [comment]
I'm going to lock this issue now as further comments will only dilute from solutions above which have seemed to be successful. If this doesn't work, please open a separate issue and link back this one :-D <3
